MinecraftForge/MinecraftForge

patches/minecraft/net/minecraft/block/Block.java.patch
patches/minecraft/net/minecraft/client/renderer/chunk/RenderChunk.java.patch
src/main/java/net/minecraftforge/client/ForgeHooksClient.java
src/main/java/net/minecraftforge/client/MinecraftForgeClient.java

Allows blocks with both translucent and opaque models to render in both passes

Allow blocks to render in multiple layers

---

patches/minecraft/net/minecraft/world/gen/structure/StructureNetherBridgePieces.java.patch
src/main/java/net/minecraftforge/common/ChestGenHooks.java

I added the nether fortress chest to ChestGenHooks with the name "netherFortress".
I tried to follow the directions on
https://github.com/MinecraftForge/MinecraftForge/wiki/If-you-want-to-contribute-to-Forge
as best as I could. =)
If anything is wrong, let me know and I'll change it!

Added Nether Fortress chest to the ChestGenHooks

---

patches/minecraft/net/minecraft/block/BlockRedstoneDiode.java.patch
patches/minecraft/net/minecraft/tileentity/TileEntityPiston.java.patch
patches/minecraft/net/minecraft/world/World.java.patch
src/main/java/net/minecraftforge/event/ForgeEventFactory.java
src/main/java/net/minecraftforge/event/world/BlockEvent.java
src/test/java/net/minecraftforge/test/NeighborNotifyEventTest.java

This event allows for mods to hook into block physics updates.
Test mod - http://pastebin.com/F1TUnVVr
This PR was created for the purpose of SpongePowered/Sponge.

Added NeighborNotifyEvent.

---

src/main/java/net/minecraftforge/fluids/FluidContainerRegistry.java

Change to FluidContainerRegistry

---

src/main/java/net/minecraftforge/fluids/FluidContainerRegistry.java

Adds a warning to the FluidContainerRegistry when a mod does something stupid! Also denies the registration.
Signed-off-by: King Lemming <kinglemming@gmail.com>

FCR Warning + Denial

---

src/main/java/net/minecraftforge/oredict/OreDictionary.java

Adds some new Ore querying functionality to reduce pointless entries.
Also attempts to size initial Hashmaps in a logical manner. (128)
Signed-off-by: King Lemming <kinglemming@gmail.com>

OreDict functionality updates.

---

src/main/java/net/minecraftforge/server/command/ForgeCommand.java

Added tab completion for forge command

Added tab completion

---

patches/minecraft/net/minecraft/client/Minecraft.java.patch

https://github.com/MinecraftForge/MinecraftForge/blob/1.7.10/patches/minecraft/net/minecraft/client/Minecraft.java.patch#L88

Add missing forge patch from 1.8 port

---

patches/minecraft/net/minecraft/client/renderer/BlockRendererDispatcher.java.patch
src/test/java/net/minecraftforge/debug/LayerBreakingTest.java

Seems when ISmartBlockModel was added someone forgot to handle the breaking Animation.

Add Block Breaking Animation for ISmartBlockModels

---

patches/minecraft/net/minecraft/inventory/ContainerBrewingStand.java.patch
patches/minecraft/net/minecraft/tileentity/TileEntityBrewingStand.java.patch
src/main/java/net/minecraftforge/common/brewing/AbstractBrewingRecipe.java
src/main/java/net/minecraftforge/common/brewing/BrewingOreRecipe.java
src/main/java/net/minecraftforge/common/brewing/BrewingRecipe.java
src/main/java/net/minecraftforge/common/brewing/BrewingRecipeRegistry.java
src/main/java/net/minecraftforge/common/brewing/IBrewingRecipe.java
src/main/java/net/minecraftforge/common/brewing/VanillaBrewingRecipe.java
src/test/java/net/minecraftforge/test/BrewingRecipeRegistryTest.java

This is based on #1786 but with the tweaks requested by Lex. (Tried to squash my commits but failed, so I figured I'd just make a new PR. Sorry.)
Adds a versatile recipe registry for the brewing stand.
Vanilla behaviour is maintained but moved to a separate class.

Added a brewing recipe registry system

---

src/main/java/net/minecraftforge/oredict/ShapedOreRecipe.java
src/main/java/net/minecraftforge/oredict/ShapelessOreRecipe.java

Same as #1793 but for the 1.8 branch

Change permission levels on ore recipes parameters

---

patches/minecraft/net/minecraft/client/renderer/EntityRenderer.java.patch
src/main/java/net/minecraftforge/client/event/EntityViewRenderEvent.java

Hook for Camera Angles, Including Roll

---

patches/minecraft/net/minecraft/client/renderer/block/model/ModelBlockDefinition.java.patch
src/main/java/net/minecraftforge/client/model/BlockStateLoader.java
src/main/java/net/minecraftforge/client/model/ForgeBlockStateV1.java
src/main/java/net/minecraftforge/client/model/IPerspectiveState.java
src/main/java/net/minecraftforge/client/model/ItemLayerModel.java
src/main/java/net/minecraftforge/client/model/MapModelState.java
src/main/java/net/minecraftforge/client/model/ModelLoader.java
src/main/java/net/minecraftforge/client/model/ModelStateComposition.java
src/main/java/net/minecraftforge/client/model/MultiModel.java
src/main/java/net/minecraftforge/client/model/TRSRTransformation.java
src/main/java/net/minecraftforge/client/model/b3d/B3DLoader.java
src/test/resources/assets/forgedebugitemlayermodel/blockstates/TestItem.json
src/test/resources/assets/forgedebugmodelloaderregistry/blockstates/CustomModelBlock.json

ItemLayerModel and B3D example mods use it, but not to the full extent.

Custom transformations in forge blockstate json.

---

patches/minecraft/net/minecraft/util/EnumFacing.java.patch

Make EnumFacing events available server-side

---

patches/minecraft/net/minecraft/client/renderer/entity/RenderManager.java.patch
src/main/resources/forge_at.cfg

Makes it possible to add extra layers to the renderer for players without having to use reflection/mod specific AT's

Make layer methods public

---

build.gradle
mdk/build.gradle
mdk/gitignore.txt

I named it with -mdk for now.. if you still want it -src let me know...

added MDK package

---

src/main/java/net/minecraftforge/fml/common/network/NetworkRegistry.java

Fix faulty channel name checking

---

patches/minecraft/net/minecraft/world/chunk/Chunk.java.patch

As seen [on the forums](http://www.minecraftforge.net/forum/index.php/topic,34245.0.html).

Fix CME when entities are spawned from EntityJoinWorldEvent

---

src/main/java/net/minecraftforge/fml/common/ModClassLoader.java

Fixes crash NPE thrown by addFile()

Initialize sources list

---

src/main/java/net/minecraftforge/server/console/ConsoleCommandCompleter.java
src/main/java/net/minecraftforge/server/console/TerminalHandler.java

This fixes a few problems with the current console command completion implementation:
- Fixed the space getting removed when completing a subcommand together with the command prefix (https://github.com/MinecraftForge/MinecraftForge/pull/2200#issuecomment-160823029)
- Added support for completing without input (basically shows a list of all commands)
- Added sorting for command completion results

Fix some issues with the console command completion

---

patches/minecraft/net/minecraft/block/Block.java.patch
patches/minecraft/net/minecraft/entity/EntityLivingBase.java.patch

Added addLandingEffects allowing mods to override landing particles

---

patches/minecraft/net/minecraft/entity/EntityAgeable.java.patch

Allow forge-type spawn-eggs to spawn child entities when clicking EntityAgeable

---

src/main/java/net/minecraftforge/client/model/ModelDynBucket.java

This allows capsules, cans, bottles,... to use the same item model for their item variant. Also it's makes much more sense.

Default bucket model is empty, allow bucket model without fluid.

---

src/main/java/net/minecraftforge/fml/common/registry/GameRegistry.java

Fixed makeItemStack ignoring stackSize

---

patches/minecraft/net/minecraft/block/BlockDropper.java.patch
patches/minecraft/net/minecraft/entity/item/EntityMinecartContainer.java.patch
patches/minecraft/net/minecraft/tileentity/TileEntityBrewingStand.java.patch
patches/minecraft/net/minecraft/tileentity/TileEntityChest.java.patch
patches/minecraft/net/minecraft/tileentity/TileEntityFurnace.java.patch
patches/minecraft/net/minecraft/tileentity/TileEntityHopper.java.patch
patches/minecraft/net/minecraft/tileentity/TileEntityLockable.java.patch
src/main/java/net/minecraftforge/common/ForgeModContainer.java
src/main/java/net/minecraftforge/items/CapabilityItemHandler.java
src/main/java/net/minecraftforge/items/IItemHandler.java
src/main/java/net/minecraftforge/items/IItemHandlerModifiable.java
src/main/java/net/minecraftforge/items/ItemHandlerHelper.java
src/main/java/net/minecraftforge/items/ItemStackHandler.java
src/main/java/net/minecraftforge/items/SlotItemHandler.java
src/main/java/net/minecraftforge/items/VanillaDoubleChestItemHandler.java
src/main/java/net/minecraftforge/items/VanillaHopperItemHandler.java
src/main/java/net/minecraftforge/items/VanillaInventoryCodeHooks.java
src/main/java/net/minecraftforge/items/wrapper/EmptyHandler.java
src/main/java/net/minecraftforge/items/wrapper/InvWrapper.java
src/main/java/net/minecraftforge/items/wrapper/SidedInvWrapper.java

Not quite complete. Still needs the default implementation and storage, which honestly I have no idea to implement in any sane way.

Add IItemHandler capability

---

patches/minecraft/net/minecraft/command/CommandHandler.java.patch

Also log the throwable to get a stacktrace.

Log unknown exceptions in commands. Resolves #2433

---

patches/minecraft/net/minecraft/world/World.java.patch

Missed this in my previous patch, my previous testing results turned out to be an odd fluke.

Test getLightOpacity(world,pos) in World as well as the chunk.

---

patches/minecraft/net/minecraft/client/renderer/EntityRenderer.java.patch
src/main/java/net/minecraftforge/client/ForgeHooksClient.java
src/main/java/net/minecraftforge/client/event/EntityViewRenderEvent.java
src/test/java/net/minecraftforge/test/FOVModifierTest.java

Enables mods to modify raw FOV directly.
Avoids modifier limit from FOVUpdateEvent.
Aware of blocks which are needed for fov change related with materials.

Added Event: EntityViewRenderEvent#FOVModifier

---

patches.mcp/minecraft/net/minecraft/entity/item/EntityMinecart.java.patch

Fix broken patches for EntityMinecart

---

src/main/java/net/minecraftforge/common/BiomeDictionary.java

Updated the biome dictionary to support 1.9

---

src/main/java/net/minecraftforge/common/BiomeManager.java

Updated BiomeManager to 1.9

---

src/main/java/net/minecraftforge/items/wrapper/CombinedInvWrapper.java
src/test/java/net/minecraftforge/debug/DynBucketTest.java

Closes #2533 
Derp, didn't notice during testing because I was only using one item at a time.

Fix CombinedInvWrapper accessing incorrect slots

---

patches/minecraft/net/minecraft/entity/item/EntityMinecart.java.patch

Some extra code got left behind during the migration from 1.8.
Closes #2601

Fix #2601 Minecart infinite acceleration

---

patches/minecraft/net/minecraft/enchantment/EnchantmentHelper.java.patch

Fix for enchantment table rolling invalid enchants

---

patches/minecraft/net/minecraft/client/entity/EntityPlayerSP.java.patch

Same as #2605 but for 1.9 branch

Allow players sized smaller than 1 block to walk into small spaces

---

patches/minecraft/net/minecraft/client/entity/EntityPlayerSP.java.patch

same changes made to the 1.9 branch

Fix pushing players inside blocks.

---

src/main/java/net/minecraftforge/event/ForgeEventFactory.java

Fix PopulateChunkEvent.Post not firing.

---

patches/minecraft/net/minecraft/client/gui/GuiScreen.java.patch
src/main/java/net/minecraftforge/fml/client/config/GuiConfig.java
src/main/java/net/minecraftforge/fml/client/config/GuiConfigEntries.java
src/main/java/net/minecraftforge/fml/client/config/GuiEditArray.java
src/main/java/net/minecraftforge/fml/client/config/GuiSelectString.java
src/main/java/net/minecraftforge/fml/client/config/GuiUtils.java

Same as #2649, but for Minecraft 1.9

Make tooltips layout in the right direction, wrap if there is no room

---

patches/minecraft/net/minecraft/client/Minecraft.java.patch
patches/minecraft/net/minecraft/client/gui/GuiControls.java.patch
patches/minecraft/net/minecraft/client/gui/GuiKeyBindingList.java.patch
patches/minecraft/net/minecraft/client/settings/GameSettings.java.patch
patches/minecraft/net/minecraft/client/settings/KeyBinding.java.patch
src/main/java/net/minecraftforge/client/settings/IKeyConflictContext.java
src/main/java/net/minecraftforge/client/settings/KeyBindingMap.java
src/main/java/net/minecraftforge/client/settings/KeyConflictContext.java
src/main/java/net/minecraftforge/client/settings/KeyModifier.java
src/main/resources/assets/forge/lang/en_US.lang

Same as #2674, but for Minecraft 1.9

[1.9] Add key binding modifiers and contexts.

---

patches/minecraft/net/minecraft/client/Minecraft.java.patch
patches/minecraft/net/minecraft/client/gui/GuiControls.java.patch
patches/minecraft/net/minecraft/client/gui/GuiKeyBindingList.java.patch
patches/minecraft/net/minecraft/client/settings/GameSettings.java.patch
patches/minecraft/net/minecraft/client/settings/KeyBinding.java.patch
src/main/java/net/minecraftforge/client/settings/IKeyConflictContext.java
src/main/java/net/minecraftforge/client/settings/KeyBindingMap.java
src/main/java/net/minecraftforge/client/settings/KeyConflictContext.java
src/main/java/net/minecraftforge/client/settings/KeyModifier.java
src/main/resources/assets/forge/lang/en_US.lang

Updated to fix issues in #2694

Re-Add key binding modifiers and contexts.

---

patches/minecraft/net/minecraft/client/settings/KeyBinding.java.patch
src/main/java/net/minecraftforge/client/settings/KeyBindingMap.java
src/main/java/net/minecraftforge/client/settings/KeyModifier.java

Fix inability to attack while holding modifier keys

---

patches/minecraft/net/minecraft/client/Minecraft.java.patch
patches/minecraft/net/minecraft/client/gui/GuiControls.java.patch
patches/minecraft/net/minecraft/client/gui/GuiKeyBindingList.java.patch
patches/minecraft/net/minecraft/client/gui/GuiScreenDemo.java.patch
patches/minecraft/net/minecraft/client/gui/GuiSpectator.java.patch
patches/minecraft/net/minecraft/client/gui/achievement/GuiAchievements.java.patch
patches/minecraft/net/minecraft/client/gui/inventory/GuiContainer.java.patch
patches/minecraft/net/minecraft/client/network/NetHandlerPlayClient.java.patch
patches/minecraft/net/minecraft/client/settings/GameSettings.java.patch
patches/minecraft/net/minecraft/client/settings/KeyBinding.java.patch
src/main/java/net/minecraftforge/client/settings/KeyBindingMap.java
src/main/java/net/minecraftforge/client/settings/KeyModifier.java

Also add Orange conflict color for modifier/key conflicts (like Ctrl and Ctrl-Z conflicting)
Conflicts are allowed and but this is kind of a "warning" color.
Related to #2692

Add modifier support to vanilla keybindings.

---

patches/minecraft/net/minecraft/world/WorldSavedData.java.patch

`WorldSavedData` has read and write NBT method, so it should implement `INBTSerializable`

Make WorldSavedData implement INBTSerializable

---

src/main/java/net/minecraftforge/client/settings/KeyModifier.java
src/main/resources/assets/forge/lang/en_US.lang

Close #2780: Add CMD localization for Mac key bindings

---

patches/minecraft/net/minecraft/client/gui/GuiIngame.java.patch
patches/minecraft/net/minecraft/potion/Potion.java.patch
src/test/java/net/minecraftforge/debug/PotionRegistryDebug.java

Add a version of Potion.renderInventoryEffect, but for the ingame HUD
Closes #2774

Add Potion.renderHUDEffect

---

src/main/java/net/minecraftforge/common/ForgeHooks.java

Stops false positives such as `um.....no`

Fix url regex

---

patches/minecraft/net/minecraft/util/ScreenShotHelper.java.patch
src/main/java/net/minecraftforge/client/ForgeHooksClient.java
src/main/java/net/minecraftforge/client/event/ScreenshotEvent.java

Remake of #2602 targeting `master`.

Add ScreenshotEvent

---

patches/minecraft/net/minecraft/client/Minecraft.java.patch
patches/minecraft/net/minecraft/client/multiplayer/PlayerControllerMP.java.patch
src/main/java/net/minecraftforge/common/ForgeHooks.java
src/main/java/net/minecraftforge/event/entity/player/PlayerInteractEvent.java

Several minor bugfixes for PlayerInteractEvent.
Remake of #2880 for master, see that PR for details.

Several bugfixes for PlayerInteractEvent

---

src/main/java/net/minecraftforge/fluids/Fluid.java
src/main/java/net/minecraftforge/fluids/FluidUtil.java

This lets fluids override what happens when they vaporize.
Water-like fluids normally vaporize by showing a poof a smoke instead of being placed in the nether.
Some volatile fluids like ethanol should explode when they are placed in the nether, this PR will allow it.

Add methods to Fluid to allow custom vaporization overrides

---

src/main/java/net/minecraftforge/common/ForgeVersion.java

Fix garbled of UTF-8 encoding Update JSON.

Read a Update JSON in UTF-8

---

src/main/java/net/minecraftforge/client/model/animation/AnimationItemOverrideList.java

Fix AnimationItemOverrideList not falling back to super

---

src/main/java/net/minecraftforge/fluids/FluidUtil.java

Fixes a javadoc confusion between filling and emptying

Fix incorrect FluidUtil doc

---

src/main/java/net/minecraftforge/fml/common/discovery/asm/ModAnnotation.java

- EnumHolder now has getters for it's data
- enum arrays work now
- nested annotations work now outside of being in arrays
Closes #2535.

Make ASMDataTable more useful

---

patches/minecraft/net/minecraft/entity/EntityAgeable.java.patch

Remake of https://github.com/MinecraftForge/MinecraftForge/pull/2318 for 1.9.4.

Made forge-type spawn eggs spawn childs, when right clicking EntityAgeable again.

---

patches/minecraft/net/minecraft/entity/player/EntityPlayerMP.java.patch
src/main/java/net/minecraftforge/event/entity/player/PlayerContainerEvent.java
src/main/java/net/minecraftforge/fml/common/network/internal/FMLNetworkHandler.java

As mentioned on IRC.
I'm not sure how clean-room this is, but it should be a good enough replacement for the PlayerOpenContainerEvent that had to be removed with the relicense.
Comments? Feedback?
(BTW, I've signed the CLA.)

Simple implementation of a Open/Close container event for 1.10

---

patches/minecraft/net/minecraft/entity/projectile/EntityThrowable.java.patch
src/main/java/net/minecraftforge/common/ForgeHooks.java
src/main/java/net/minecraftforge/event/entity/ThrowableImpactEvent.java

Updated version of #2340 
Dead simple

Add throwable impact event

---

patches/minecraft/net/minecraft/client/renderer/ItemRenderer.java.patch
src/main/java/net/minecraftforge/client/ForgeHooksClient.java
src/main/java/net/minecraftforge/client/event/RenderHandEvent.java
src/main/java/net/minecraftforge/client/event/RenderHandEventSpecific.java

Cleaner version of #2938. Closes #2747

Add hand-specific render event

---

src/main/java/net/minecraftforge/client/ForgeHooksClient.java

I'm not sure why this is still TODO, it seems to work fine.
Maybe @RainWarrior just didn't have anything to test it with?
I've tested this with C&B, and I didn't have any issues.

Use extended state for breaking models.
