src/main/java/net/minecraftforge/common/ForgeModContainer.java, src/main/java/net/minecraftforge/common/MinecraftForge.java
The same as the 1.8 fix, except for the 1.7.10 branch.
Fixes the versionCheck config option not working.
=> Fix versionCheck config option

patches/minecraft/net/minecraft/world/chunk/Chunk.java.patch
This is @LexManos's proposal for @CovertJaguar's fix. We need it, it's causing lots of issues!
=> fix shouldRefresh being too broad in tile entity update

src/main/java/net/minecraftforge/client/ForgeHooksClient.java, src/main/java/net/minecraftforge/fluids/Fluid.java
Just now uses TextureAtlasSprites (which is what all fluid icons should be in 1.7 anyways), and gets the water and lava icons from the TextureMap directly due to the removal of the method from the BlockLiquid class. Let me know if there's a place that I missed.
=> Re-enabled Icon setting for Fluids

src/main/java/net/minecraftforge/fluids/FluidTank.java
If the Empty flag was set, the tank would not correctly read the data, keeping the outdated FluidStack instead. This is especially relevant with updatable TileFluidHandler TEs.
=> Fix fluid tanks incorrectly reading NBT when empty

src/main/java/net/minecraftforge/fluids/BlockFluidClassic.java
Set the destination block the to the fluid.
In the previous code the destination block was still Air and would 
cause a crash because air doesn't have a property for LEVEL
The new version of the code will set the block to the Fluid block and set the fluid's level property.
=> Fixes issue #1552 Where the flowIntoBlock method was not setting the Block to the fluid and causing crashes

src/main/java/net/minecraftforge/common/ForgeModContainer.java
`getPersistentID()` returns the same UUID as `getGameProfile().getId()` when the player is online, but when they are offline a UUID based on the hash of the username is returned. This prevents the returned UUID from ever returning `null`, making sure we can cache the offline players' UUID -> username mappings.
=> Minor tweak to UsernameCache to also cache usernames of offline players

src/main/resources/forge_at.cfg
This is a remake of #1682, with the fixed merge conflicts.
This publics the VALUES array and HORIZONTALS array in EnumFacing, thus giving modders access to these arrays, much like ForgeDirection had.
I don't believe this needs an example mod, as all this is doing is giving modders access to something similar as to what was in ForgeDirection.
=> Added ATs for EnumFacing

patches/minecraft/net/minecraft/entity/player/EntityPlayer.java.patch
#1652 Targeted at master branch
Example:
```java
@SubscribeEvent
public void playerLogin(PlayerEvent.PlayerLoggedInEvent event) {
if (isAdmin(event.player)) {
ChatComponentText prefix = new ChatComponentText("[Admin] ");
prefix.getChatStyle().setColor(EnumChatFormatting.RED);
event.player.addPrefix(prefix);
}
}
```
=> Ability to add prefixes and suffixes to the player's display name

patches/minecraft/net/minecraft/entity/EntitySpawnPlacementRegistry.java.patch
Current spawner implementation checks the EntitySpawnPlacementRegistry hashmap to check where a entity should spawn
as there is no way to modify this without the use of reflection or a AT, you can not specify where you want your entity to spawn
adding this helper method will allow developers to specify where they want their entity to spawn.
=> Add method to set entity placements

patches/minecraft/net/minecraft/enchantment/Enchantment.java.patch
Secondary enchantments is implemented by overriding the ```canApply``` method. Reversing the delegation between ```canApply``` and ```canApplyAtEnchantingTable``` should fix them giving same result for both cases. Fix  #1428.
=> Fixed enchanting table applying secondary enchs.

src/main/resources/assets/forge/lang/README.txt, src/main/resources/assets/forge/lang/de_DE.lang, src/main/resources/assets/forge/lang/es_ES.lang, src/main/resources/assets/forge/lang/fr_FR.lang, src/main/resources/assets/forge/lang/ru_RU.lang
Now the link to the crowdin project is more visible, it should avoid pull request regarding translations.
I also removed the old translations because they clash with the one on the project crowdin.
For example, in the crowdin project fr_FR is 100 % translated, but in final jar file the file fr_FR.lang is incomplete, there is what is currently on github : 
There is the same problem with all the languages that have a translation on github
=> Remove translation and add a note for contributors

src/main/java/net/minecraftforge/client/GuiIngameForge.java
This has actually been a long standing bug with `GuiIngameForge` as far as I can tell (I could find it even in 1.6.4). Probably not worth it to fix for 1.7 though.
[With forge](http://i.imgur.com/JwMAJRy.png)
[Without forge](http://i.imgur.com/ee7hPxF.png)
Also reported [on the forums](http://www.minecraftforge.net/forum/index.php/topic,28568.0.html).
=> Fix jukebox message being too low

patches/minecraft/net/minecraft/entity/Entity.java.patch, patches/minecraft/net/minecraft/entity/EntityLivingBase.java.patch, src/main/java/net/minecraftforge/event/ForgeEventFactory.java, src/main/java/net/minecraftforge/event/entity/EntityMountEvent.java
This event gets fired whenever a entity mounts/dismounts another entity, like when a players right-clicks an empty minecart, or right-clicks a horse with a saddle. It contains the entity mounting, and the entity that's being mounted. If it's canceled, the entity does not mount/dismount.
Here's the example mod: 
http://pastebin.com/EbpHgvCJ
=> Add an EntityMountEvent.

patches/minecraft/net/minecraft/client/entity/EntityPlayerSP.java.patch, patches/minecraft/net/minecraft/world/World.java.patch, src/main/java/net/minecraftforge/event/ForgeEventFactory.java, src/main/java/net/minecraftforge/event/entity/PlaySoundAtEntityEvent.java
Added newVolume and newPitch to PlaySoundAtEntityEvent. Deprecated ForgeEventFactory.onPlaySoundAt, added replacement method ForgeEventFactory.onPlaySoundAtEntity.
This is the second iteration of a solution for [this issue](https://github.com/MinecraftForge/MinecraftForge/issues/1750).
_I am not good with Forge development, pls to halp._
=> Added newVolume and newPitch to PlaySoundAtEntityEvent.

patches/minecraft/net/minecraft/tileentity/TileEntity.java.patch
This PR adds `getTileData()` to `TileEntity` in the same way that `Entity` has `getEntityData()`.
It can be useful for saving custom data in vanilla TEs.
=> Add getTileData() to TileEntity

patches/minecraft/net/minecraft/client/renderer/entity/RenderPlayer.java.patch, src/main/java/net/minecraftforge/client/event/RenderPlayerEvent.java
RenderPlayerEvent.Specials was removed because the special effects are done in the LayerRenderer now.
=> Reimplement RenderPlayerEvent that was removed in the port to 1.8 from 1.7.10.

src/main/java/net/minecraftforge/fluids/FluidRegistry.java
FluidRegistry:
```java
static BiMap<String, Fluid> fluids = HashBiMap.create();
static BiMap<Fluid, Integer> fluidIDs = HashBiMap.create();
...
public static boolean registerFluid(Fluid fluid)
{
if (fluidIDs.containsKey(fluid.getName()))
^^^^^^^
```
There is definitely should be fluids instead fluidIDs. This mistake broke many mods.
=> [1.7.10] Fix FluidRegsitry.registerFluid

src/main/java/net/minecraftforge/fluids/FluidContainerRegistry.java, src/main/java/net/minecraftforge/fluids/FluidRegistry.java
Fixes FluidContainerRegistry keys in such a way that they are ID independent, which was *actually* the goal in the first place.
Also clarifies the multiple Fluid registration error message a bit.
=> 1.7.10 fluid

src/main/java/net/minecraftforge/fluids/FluidContainerRegistry.java, src/main/java/net/minecraftforge/oredict/OreDictionary.java
Getting Ore Names for a non-existent ore will no longer automatically add that Name to the list nor generate an ID.
Tweaks a warning message in the FluidContainerRegistry. No functionality change.
Signed-off-by: King Lemming <kinglemming@gmail.com>
=> Adjusts OreDictionary to prevent invalid registrations.

patches/minecraft/net/minecraft/client/renderer/chunk/RenderChunk.java.patch
This allows any extending classes to define their own implementation of `BlockRendererDispatcher`.
The alternative to this (which I'm currently using) is to replace the vanilla instance with the custom instance in every `preRenderBlocks`/`postRenderBlocks` call, but that's not reliable and might cause other issues.
Alternatively this could be moved to a method that would return the dispatcher instance and extending classes would override the method.
=> Extracted the creation of RegionRenderCache into a method for extendability

patches/minecraft/net/minecraft/util/EnumWorldBlockLayer.java.patch
Removed "@SideOnly(Side.CLIENT)" from EnumWorldBlockLayer to solve a crash which occurs if something attempts to get the list of methods in Block or a subclass of Block. This is caused by "Block.canRenderInLayer(EnumWorldBlockLayer)" not being removed on the server side, so the server would attempt to load EnumWorldBlockLayer when it does not exist.
=> Removed @SideOnly(Side.CLIENT) from EnumWorldBlockLayer.

patches/minecraft/net/minecraft/client/Minecraft.java.patch, patches/minecraft/net/minecraft/util/Session.java.patch
Exact same thing as #1826, but for 1.8. Read there for info.
Also, hooray for less derpy Minecraft patch.
=> [1.8] Fixes MC-52974: Host's skin doesn't load in LAN

patches/minecraft/net/minecraft/world/World.java.patch
This will fix a bug which causes the light value not to update if a block's light value depends on its block state, using an implementation of getLightValue(IBlockAccess, BlockPos). It's a simple change to make setBlockState compare the light value before and after setting the block state.
=> Make World.setBlockState check whether the light value from getLightValue(IBlockAccess, BlockPos) has changed.

src/main/java/net/minecraftforge/common/ChestGenHooks.java
Forced the nether fortress chest loot to initialize in ChestGenHooks like the other types.
=> Initialized the Nether Fortress chest loot

fml/src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java
Fixes crashes [like this](http://www.minecraftforge.net/forum/index.php/topic,30512.0.html).
I just made it "quick and dirty", it will just swallow any RuntimeExceptions without message. But really we should catch (all) Exceptions and store *those* for later, not just the message. If that is desired I'll update this accordingly.
=> Fix crash when texture loading throws RuntimeException without message

patches/minecraft/net/minecraft/client/gui/FontRenderer.java.patch
1. Add additional readGlyphSizes call in onResourceManagerReload for allowance to specify custom glyph sizes in resourcepacks (now it works only after restart).
2. Remove artificial restriction of max glyph size of unicode.
3. Remove force shadow shift for unicode font.
Some screenshots:
Vanilla (almost), default resource pack:
Vanilla, custom resource pack:
Patch (without shadow), custom resource pack:
Patch with shadow support:
*Possible also can be useful for 1.7.10 branch*
=> Add true support for unicode fonts

patches/minecraft/net/minecraft/entity/EntityHanging.java.patch
Very simple patch to allow Item Frames to be placed on blocks with solid faces.
=> Allow placing item frames on Solid Block Faces (isSideSolid)

patches/minecraft/net/minecraft/client/renderer/block/model/ModelBlockDefinition.java.patch, src/main/java/net/minecraftforge/client/model/BlockStateLoader.java, src/main/java/net/minecraftforge/client/model/ForgeBlockStateV1.java, src/main/java/net/minecraftforge/client/model/IModelCustomData.java, src/main/java/net/minecraftforge/client/model/IRetexturableModel.java, src/main/java/net/minecraftforge/client/model/ISmartVariant.java, src/main/java/net/minecraftforge/client/model/ModelLoader.java, src/main/java/net/minecraftforge/client/model/MultiModel.java, src/main/resources/forge_at.cfg, src/test/java/net/minecraftforge/debug/ForgeBlockStatesLoaderDebug.java, src/test/resources/assets/forgeblockstatesloader/blockstates/cobblestone_wall.json, src/test/resources/assets/forgeblockstatesloader/blockstates/mossy_cobblestone_wall.json, src/test/resources/assets/forgeblockstatesloader/models/block/wall_connect.json, src/test/resources/assets/forgeblockstatesloader/models/item/cobblestone_wall.json, src/test/resources/assets/forgeblockstatesloader/models/item/mossy_cobblestone_wall.json
Due to the sever amount of whining. And nobody else stepping up to try and handle this. I've taken a crack at it.
This is the first pass at re-working the model formats that Minecraft provides.
This is done after a non-insignificant amount of discussion with Mojangsters, about the possible changes coming to future versions of their system. The basic concept is close to what I understand they want to go forward with so ya.
What is the point of this?
To once and for all make the 'OMFG THE SKY IS FALLING' people shut up.
So lets get to it this is what it does.
It allows you to use a less-verbose blockstates.json file. 
What before would be represented by this: https://github.com/Deadrik/TFC2/blob/master/src/Resources/assets/tfc2/blockstates/grass.json and …
=> Hook BlockState's Json loading to add support for simplified Forge format.

patches/minecraft/net/minecraft/client/renderer/ItemRenderer.java.patch, patches/minecraft/net/minecraft/client/renderer/tileentity/RenderItemFrame.java.patch, patches/minecraft/net/minecraft/entity/item/EntityItemFrame.java.patch
This small addition adds type checks to `ItemRenderer`, `RenderItemFrame`, and `EntityItemFrame`. This enables ItemMaps to be rendered via pre-existing code without the need to reinvent any wheels. There is no need to write OpenGL, and allows modders to make custom maps by simply extending `ItemMap` and overriding `updateMapData` to transform the data from within the map itself to create the desired output.
=> Added ItemMap type check to item frames and ItemRenderer, enabling vanilla style rendering for custom ItemMaps

patches/minecraft/net/minecraft/entity/EntityLivingBase.java.patch, src/main/java/net/minecraftforge/event/ForgeEventFactory.java, src/main/java/net/minecraftforge/event/entity/living/LivingExperienceDropEvent.java
This event allows modders to change the amount of experience entitys drop when they die.
While there is EntityLiving.experienceValue, the code that drops the experience calls EntityLivingBase.getExperiencePoints which is overridden in for example EntityAnimal to return a random value instead of experienceValue.
Example Mod: http://pastebin.com/kSptA30S
Increases the experience dropped by ALL entitys by a factor of 10.
Remake of https://github.com/MinecraftForge/MinecraftForge/pull/1223, targeted at 1.8.
=> Added LivingExperienceDropsEvent to change how much experience an entity drops

src/main/java/net/minecraftforge/common/BiomeDictionary.java
It appears that there are two shortcomings in the BiomeDictionary.
First, when a new Type is created, the typeInfoList is expanded incorrectly. It should be expanded to
ret.ordinal()+1
Second, EnumSets are great, fantastic even, but they come with stipulations. Since they use bitwise flags and ordinals, they break upon addition of new Enum elements. To fix this, they must be re-instantiated when a new Type is added. This could also be fixed by simply using a regular HashSet instead of an EnumSet.
Test case:
http://pastebin.com/VhNB0C47
This is #1933 for 1.8.
=> Two exceptions in BiomeDictionary

src/main/java/net/minecraftforge/common/WorldSpecificSaveHandler.java
If the dat file isn't in the dimension specific folder but is present in the vanilla data folder then copy it over.
=> Fixes #1747

patches/minecraft/net/minecraft/block/Block.java.patch, src/main/java/net/minecraftforge/common/ForgeHooks.java
Block.getPickBlock was patched in 1.7 but was overlooked in 1.8.
Closes: https://github.com/MinecraftForge/MinecraftForge/issues/1709
=> Player sensitive version of Block.getPickBlock

patches/minecraft/net/minecraft/client/gui/GuiScreen.java.patch, patches/minecraft/net/minecraft/client/gui/inventory/GuiContainer.java.patch, src/main/java/net/minecraftforge/client/event/GuiScreenEvent.java
Problem:
GuiScreen consumes keyboard and mouse input in such a way that the existing events aren't fired. (it uses Mouse.next() and Keyboard.next()).
There is no way to detect these events without using .next() first, which messes up keyboard and mouse detection for everything.
Use case 1:
I'm writing [an NEI alternative that isn't a coremod](https://github.com/mezz/JustEnoughItems). It needs to know about keyboard and mouse events when a GuiScreen is open. My current options are not good, and the current implementation is broken.
Use case 2:
Forestry backpacks can't be opened from the inventory because there is no way to detect a click or key press. With the mouse event and the ability to getTheSlot() from a guiContainer, we can detect a mouse click or key press and open the backpack …
=> Add GuiScreenEvents for keyboard and mouse input

src/main/java/net/minecraftforge/client/model/b3d/B3DLoader.java
In the current B3DLoader class, in the cache map, the values are retrieved by a specially copied ResourceLocation - but they are added to the map identified by the originally passed ResourceLocation.
If the original ResourceLocation is a B3DMeshLocation, the equals method returns false when being compared to the cloned ResourceLocation, and the loadModel method ceases to work.
This PR fixes this bug by putting the model into the map using the cloned ResourceLocation.
=> Bugfix for B3DLoader

src/main/java/net/minecraftforge/common/brewing/VanillaBrewingRecipe.java
Oversight on my part,
If the ingredient doesn't return true in Item.isPotionIngredient, Items.potionitem.getEffects(stack) returns null, causing an NPE to be thrown later on.
This invalidates #1947.
=> Fixed NPE when calling canBrew

src/main/java/net/minecraftforge/common/BiomeDictionary.java
The biome dictionary guessing logic looks for stained clay as the *top* block, while the vanilla mesa biome uses stained clay as the *filler* block. This causes the dictionary to miss mutated vanilla mesa biomes, for example. This patch fixes that.
=> fix logic for guessing mesa tag in biome dict

patches/minecraft/net/minecraft/client/renderer/block/statemap/StateMap.java.patch, src/test/java/net/minecraftforge/debug/ForgeBlockStatesLoaderDebug.java
The standard StateMap (built with StateMap.Builder) does not respect the blocks domain and therefore always defaults to "minecraft:foo". A mapping therefore always maps to "minecraft:foo#state" which can't be found, instead of "mymod:foo#state".
The debug block and mapper added are solely there for the error message to confirm that the patch works.
Without Patch:
```[FML]: Model definition for location minecraft:TypeA#normal not found```
With Patch:
```[FML]: Model definition for location forgeblockstatesloader:TypeA#normal not found```
=> Fix StateMap always mapping properties to the "minecraft" domain

fml/src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java, src/main/java/net/minecraftforge/client/GuiIngameForge.java
Tested by adding `dependencies = "required-after:IDoNotExist@[0,1]"` to LayerBreakingTest.
=> Fixed error GUIs showing a white screen

src/main/java/net/minecraftforge/fluids/BlockFluidClassic.java
The method `isSourceBlock` was comparing a blockstate with a block, which always returns false.
=> Fix source block check for BlockFluidClassic

src/main/java/net/minecraftforge/client/model/ForgeBlockStateV1.java
This fixes two bugs in the Forge blockstates loader:
Forge blockstates jsons that remove submodels caused an NPE in the loader.
Deep cloning of v1 Variants didn't clone submodels properly, causing some unexpected behavior when applying parent variant data to submodels.
=> Fixed two bugs with the Forge blockstates v1 loader.

patches/minecraft/net/minecraft/item/ItemBlock.java.patch
This fixes the issue that signs with NBT data don't place their data when the item is clicked on a block.
The problem was originally discovered in: https://github.com/SpongePowered/Sponge/issues/289
I fixed the issue by comparing forge's patch to vanilla's patch.
So I opened a clean 1.8.7 jar (in jd-gui) and after some snooping around the classes I identified some key classes (by comparing them to 1.8 classes).
Class `aar` is `ItemSign`, class `yo` is `ItemBlock`, the method `public static boolean a(adm ☃, wn ☃, cj ☃, zx ☃)` is `setTileEntityNBT`
within that method there is the line:
```java
if ((!☃.D) && (☃.F()) && (!☃.ap().h(☃.cd()))) {
return false;
}
```
Comparing this to forge's patch and some more class investigation the line is expanded to:
```java
if ((!worldIn.isRemote) && …
```
=> Fix placing signs with NBT prompting for text

src/main/java/net/minecraftforge/common/BiomeManager.java, src/main/java/net/minecraftforge/common/EnumPlantType.java, src/test/java/net/minecraftforge/debug/EnumPlantTypeTest.java
This commit includes three changes:
1. The `EnumPlantType.java` with a new hook added, not considering to break the compatibility.
2. The `BiomeManager.java` with an incorrect usage of `EnumHelper` in subclass (enumeration) `BiomeType` fixed. When calling that method it will throw an NPE on [this line](https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/common/BiomeManager.java#L180) because `EnumHelper` returns null when it cannot function properly.
3. The `EnumHelperTest.java` with 2 tests, to check whether those two things works. (When I run it with this commit now it does not post any warning, of course this change compiles)
Hope any one of those 321 watchers to leave a comment here. I am glad to listen to your suggestions and going to improve …
=> Add hook for adding EnumPlantType and fixed npe in BiomeType

patches/minecraft/net/minecraft/block/BlockDoublePlant.java.patch, patches/minecraft/net/minecraft/block/BlockOldLeaf.java.patch, patches/minecraft/net/minecraft/item/ItemShears.java.patch
This pull request aims to fix two issues, the first is that onSheared runs in creative mode and the second is that in survival both the harvestBlock logic and the onSheared logic runs. In order to restore vanilla functionality this patch does two things.
1. Adds a check into ItemShears to see if the player attempting to break a block with shears is in creative mode, aborting the shear logic if so.
2. Keeps existing harvestBlock functionality while removing the base logic that destroys and drops the blocks letting forge handle that in onSheared.
This fixes https://github.com/SpongePowered/Sponge/issues/283 and makes forge behavior match vanilla. Note that shearing of entities likes sheep remains untouched because vanilla does drop wool in creative mode when shearing a sheep.
This probably …
=> Fix harvest logic running in addition to shearable logic

patches/minecraft/net/minecraft/client/renderer/ItemRenderer.java.patch, src/main/java/net/minecraftforge/client/event/RenderBlockOverlayEvent.java, src/main/java/net/minecraftforge/event/ForgeEventFactory.java
Seems to have been missed during 1.8 update.
=> Re-introduce RenderBlockOverlayEvent

patches/minecraft/net/minecraft/client/resources/SkinManager.java.patch
When running forge in a dev environment (untested in obf), two calls are made to `fillProfileProperties` on the same UUID which results in the rate limit blocking the second call.
See my comment on https://github.com/SpongePowered/SpongeCommon/issues/117#issuecomment-128977276 for a more detailed diagnostic.
Steps to reproduce the problem:
* Setup a clean forge development workspace
* Launch Client
* Create new single player world
* `com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time`
=> Use already provided profile for the player's own skin

patches/minecraft/net/minecraft/item/crafting/FurnaceRecipes.java.patch
Since the furnace iterates through the list and stops when it finds the first valid recipe, anything added that conflicts with something that's already registered won't ever be used.
So it's be better to just not even add them to the list, which can reduce its size and therefore improve performance.
This would have zero effect on existing mods, since (as already mentioned) any recipes they add that conflict were never used in the first place.
=> Disallow conflicting furnace recipes

patches/minecraft/net/minecraft/init/Bootstrap.java.patch, patches/minecraft/net/minecraft/item/ItemMonsterPlacer.java.patch
The dispenser action does not take into account the generalization introduced in c158af902f2a689f612fd20427b5a1590fc2f1ba to allow modders to register spawn eggs, activating a spawn egg for a modded mob simply causes the egg to vanish.
This fixes this by simply using the new `spawnCreature` method which uses the unique mob name instead of mob id. This required this method to become public.
=> Fix dispenser action for modded spawn eggs

src/main/java/net/minecraftforge/fml/common/eventhandler/EventBus.java
Re-pull of #2103 targeting 1.8.
There is currently no way to check if an event handler has been registered or not.
But when trying to unregister a not-registered event handler, Minecraft crashes with a NullPointerException.
This is a simple fix to prevent such crashes.
=> Fix a possible crash in EventBus

fml/src/main/java/cpw/mods/fml/common/eventhandler/EventBus.java
There is currently no way to check if an event handler has been registered or not.
But when trying to unregister a not-registered event handler, Minecraft crashes with a NullPointerException.
This is a simple fix to prevent such crashes.
(Same applies to 1.8 and newer)
=> Fix possible crash in EventBus

patches/minecraft/net/minecraft/entity/player/EntityPlayer.java.patch, src/main/java/net/minecraftforge/event/ForgeEventFactory.java, src/main/java/net/minecraftforge/event/entity/player/PlayerSetSpawnEvent.java, src/test/java/net/minecraftforge/test/PlayerSetSpawnTest.java
Fired just before a player's spawn is set, allows you to prevent a user from setting spawn. As well as knowing when their spawn is being changed.
For example see: PlayerSetSpawnTest
If I'm missing something please let me know so I can fix it.
=> Add PlayerSetSpawnEvent

src/main/java/net/minecraftforge/fml/common/launcher/FMLServerTweaker.java, src/main/java/net/minecraftforge/fml/common/launcher/FMLTweaker.java, src/main/java/net/minecraftforge/fml/relauncher/FMLLaunchHandler.java
This adds `org.apache.` and `com.google.common.` to the `LaunchClassLoader` exclusion list for server, just like they are on the client.
I also moved the exclusions to common place which makes it less likely for the list to go out of sync for client/server.
An example dedicated server crash is when trying to use Sponge and CodeChickenCore.
You end up with some guava classes loaded via the LCL and others on ACL
Examples of crashes (which I believe this PR will fix)
https://forums.spongepowered.org/t/crash-on-launch-mixins/7553
https://forums.spongepowered.org/t/mod-conflict-list/8350 (CCC + NEI)
Error messages look like the following:
> java.lang.LinkageError: loader constraint violation: when resolving method "com.google.common.io.Resources.readLines(Ljava/net/URL;Ljava/nio/charset/Charset …
=> Add Guava and Apache to LaunchClassLoader exclusion list on server

src/main/java/net/minecraftforge/client/model/ModelLoader.java
Fixed a bug with item model loading that would occur if ModelBakery.addVariantName() was called with the same string location parameter for 2 different items, and the string pointed to a location that didn't exist, where ModelLoader.loadAnyModel() would substitute the blockdefinition in for the item model, but wouldn't remove the original input location from the loadingModels list, which would cause the location from the second call to throw an IllegalStateException even though that location now has a model.
=> Fixed a bug with item model loading 

patches/minecraft/net/minecraft/client/network/NetHandlerPlayClient.java.patch, patches/minecraft/net/minecraft/potion/PotionEffect.java.patch
The fix from https://github.com/MinecraftForge/MinecraftForge/pull/2108 in simplified form.
=> Fix Potion IDs above 127

src/main/java/net/minecraftforge/fml/client/config/GuiSelectString.java
Fixed a bug with GuiConfigEntries.SelectValueEntry that caused the config option name to overlap with the selectable values, fixes #2114
Lex, unless I missed something, I am following Forge code formatting guidelines. The braces are on new lines, and I used spaces instead of tabs.
=> Fixed a bug with GuiConfigEntries.SelectValueEntry

src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java
Fixes #2100
It now iterates over `badTextureDomains` instead of `missingTextures.keySet()` as a domain can have broken textures without any missing textures.
It only prints "The missing resources for domain..." when the domain has missing resources.
=> Fix texture error message for broken textures

src/main/java/net/minecraftforge/fml/common/registry/GameData.java
GameData.findBlock first checked containsKey on the Block registry, but the registry only contains ResourceLocations, hence the checked String is never in there.
While fixing this bug I also discovered that `containsKey` generally is broken, if desired I will fix that, too.
=> Fix GameData.findBlock

src/main/java/net/minecraftforge/fml/common/registry/GameData.java
This fixes `GameData.createRegistry` where the class implements any interface, directly and indirectly, will currently crash due to interfaces having `null` as their superclass via Reflection API.
The associated issue is #2176
=> Fix a possible NPE when checking supertypes of interfaces.

patches/minecraft/net/minecraft/client/renderer/entity/layers/LayerArmorBase.java.patch
This else statement prevents custom armor colors from being uncolored before rendering
=> Allows Custom Armor Coloring to be done easily

src/main/java/net/minecraftforge/fml/common/network/handshake/NetworkDispatcher.java
I made this #1164 PR which is supposed to respawn clients in the overworld if they login and are in a dimension that no longer exists on the server. The "pre-sending" of the dimension id to the client to allow higher dimension ids somewhat breaks that as it sends the non existent dimension instead of the overworld. Therefore the clients world is set to null which prevents him from logging in (And spams tons of errors in his console). If the client just tries to login again it fixes itself but it's still annoying. 
This PR fixes that issue by making the dimension hack thingy check whether the dimension actually exists before sending it to the player. If it doesn't it just sends the Overworld (0).
=> Fixes Client Login Issue when logging into a non existent dimension

patches/minecraft/net/minecraft/tileentity/TileEntityFurnace.java.patch, src/main/java/net/minecraftforge/event/ForgeEventFactory.java, src/main/java/net/minecraftforge/event/FuelBurnTimeEvent.java
Adds an event Hook that allows modification of burn times for items that the vanilla fuel handler thinks it recognizes.
Fixes MinecraftForge/FML#559
...and allows mod developers to proceed with fixes for:
- MinecraftModArchive/Dendrology#1
- ForestryMC/ForestryMC#469
- ForestryMC/ForestryMC#930
- ForestryMC/ForestryMC#960
Example:
public class FuelHandler
{
@SubscribeEvent
public void onFuelBurnTime(FuelBurnTimeEvent event)
{
if (event.fuel.getItem().equals(MyStuff.myItem))
{
event.burnTime = 300;
event.setResult(Result.ALLOW);
}
}
}
=> Fuel Handling Fix

src/main/java/net/minecraftforge/common/BiomeManager.java
Adding a `BiomeManager.BiomeType` after `BiomeManager` has been loaded won't extend the `biomes` array correctly (the new array will be the same length as the existing one).
`BiomeManager.getBiomes` can crash with an `ArrayIndexOutOfBoundsException` if called with a `BiomeManager.BiomeType` whose ordinal is equal to the `biomes` array's length.
[Test case](https://github.com/Choonster/ForgeBiomeManagerTestMod/blob/master/src/main/java/com/choonster/forgebiomemanagertestmod/ForgeBiomeManagerTestMod.java)
[Crash report](https://gist.github.com/Choonster/36998b9778fe226095bc)
=> BiomeManager: Fix off-by-one errors

patches/minecraft/net/minecraft/server/MinecraftServer.java.patch
This is especially noticable when you repeatedly rejoin a singleplayer world. You will end up with tons of WorldServer instances that are not getting gc'd, filling up your memory.
I'm not sure why / how these were switched in 1.8.8 but since MinecraftServer.stopServer() only actually stops the server when serverStopped is still false the server ends up not being stopped.
=> Fixed: Server not being stopped, causing Worlds to stay loaded

patches/minecraft/net/minecraft/block/Block.java.patch, patches/minecraft/net/minecraft/block/BlockSlab.java.patch, patches/minecraft/net/minecraft/block/BlockStairs.java.patch
By default calls isOpaqueCube which is the original behavior prior to this patch.
Patch allows a block to claim its own opaque sides rather then requiring all 6 faces to be opaque.
=> Added doesSideBlockRendering to provide finer grain face culling.

src/main/java/net/minecraftforge/fml/common/ModClassLoader.java
=> Fix a typo in jar detection

patches/minecraft/net/minecraft/potion/PotionEffect.java.patch
PR to branch 1.8.8 of https://github.com/MinecraftForge/MinecraftForge/pull/2265
Prevents the whole loop from running if a matching item has been found, as well as replacing duplicate code with a method call
=> [1.8.8] Minor Fixes to PotionEffect.java.patch

patches/minecraft/net/minecraft/item/Item.java.patch, src/main/java/net/minecraftforge/client/GuiIngameForge.java
I want to use the vanilla feature to inform players of the mode of a tool when they change it, or switch back to the tool, this allows for an item to tweak the final tip that is displayed.
It was either this or some extra displayName hook that is called by ItemStack.getDisplayName() or some event... but I seem to recall that events that let you override other items like that are not preferred.
After thinking about it this seems more in line with the intended purpose. If someone has any better ideas I'm all ears.
=> Add getHighlightTip allowing a item to override its displayed renderToolHightlight

patches/minecraft/net/minecraft/client/gui/GuiChat.java.patch, src/test/java/net/minecraftforge/test/ClientCommandTest.java
It appears that vanilla changed the way auto-completion is handled (the text is written into the input field in different parts of the code), requiring an additional stripping of the gray/reset color codes.
=> Fix client side command auto-complete not working correctly.

patches/minecraft/net/minecraft/command/CommandBase.java.patch
Honestly, I should have caught this when I made the original PR a year ago.
Things like /msg, /me, and /say
=> Add links for messages and other commands

patches/minecraft/net/minecraft/entity/item/EntityItem.java.patch
Updated version of #2347 since I force pushed and github wouldn't let me reopen.
This PR resolves an issue with item entities in 1.8 and the /give command.
In 1.8.x, the vanilla /give command seemingly appears to spawn an item entity in from of you, which you then pick up.
However that is not the actual case.
Looking in class CommandBase
Line 70: The item is added directly to the player inventory
Then we enter an if. If the remainder stacksize is 0 or less (inventory had room), then we call player.dropPlayerItem, and then call func_174870_v() on it, which sets the age to 5999 and pickup delay to 32767. This effectively spawns an item in from of the player that immediately dies (because the vanilla default max age is 6000), just for the visual effect. Why that instead of directly spawning …
=> Fix bug with /give command and items with larger than default lifespans

patches/minecraft/net/minecraft/client/gui/GuiScreen.java.patch, src/main/java/net/minecraftforge/client/event/GuiScreenEvent.java
JEI needs to draw above the gui's background but below the gui's tooltips.
https://github.com/mezz/JustEnoughItems/issues/86
By adding this event, anything that needs to draw beside a gui correctly can do so.
=> Add DrawScreenBackgroundEvent

patches/minecraft/net/minecraft/entity/player/EntityPlayer.java.patch, src/main/java/net/minecraftforge/event/ForgeEventFactory.java, src/main/java/net/minecraftforge/event/entity/player/SleepingLocationCheckEvent.java, src/test/java/net/minecraftforge/test/NoBedSleepingTest.java
Currently game wakes up players, if they have no bed blocks under them.
This makes implementing features like sleeping bags in item form impossible without using coremods.
This PR:
- allows modders to override default bed check via event.
- adds `Block.isBed` checks where game can behave incorrectly (e.g. getting properties that don't exist on block).
- changes game logic to not set spawn after waking up without bed (it was mostly useless or even harmful, since failing bed block check during respawn will reset spawn point).
Test mod with simple "sleeping pills" item provided in PR.
=> Allow sleeping without bed block under player

patches/minecraft/net/minecraft/server/dedicated/ServerHangWatchdog.java.patch
Prevents the following from happening:
```
[23:28:04] [Server thread/INFO]: Done (10.520s)! For help, type "help" or "?"
[23:28:04] [Server Watchdog/FATAL]: A single server tick took 71.62 seconds (should be max 0.05)
[23:28:04] [Server Watchdog/FATAL]: Considering it to be crashed, server will forcibly shutdown.
[23:28:04] [Server Watchdog/ERROR]: This crash report has been saved to: /.../run/./crash-reports/crash-2015-12-30_23.28.04-server.txt
[23:28:06] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2034ms behind, skipping 40 tick(s)
```
=> Skip hang detection on first run of the server hang watchdog

src/main/resources/log4j2_server.xml
Currently the Vanilla log file (in `logs/latest.log`) will get all console formatting codes written to it because unlike for all other file handlers it doesn't have the formatting code stripping set up. Other than encoding issues, I think this also causes problems like shown in https://forums.spongepowered.org/t/strange-r-appear-in-console-when-someone-types/10913/5?u=minecrell for certain control panels that read this log file.
With this change the formatting codes should get stripped for the Vanilla log file identically to all the other log files created by Forge.
=> Strip console formatting codes for Vanilla log file

patches/minecraft/net/minecraft/client/gui/inventory/GuiContainer.java.patch
Taking an item out of a slot used to immediately drop it to the ground afterwards if the slot is not within the GUI boundaries. This PR ensures that items will no longer fall through slots below the cursor.
My mod TrashSlot adds an additional slot to the player inventory, which is positioned outside of the GUI boundaries. Increasing the boundaries is not an option as GuiInventory's background rendering depends on it. I've been using a coremod to fix this issue in the past.
=> Fix items being dropped through slots outside GUI boundaries

patches/minecraft/net/minecraft/tileentity/TileEntityBeacon.java.patch
This corrects the passed BlockPos to be the block being checked, currently the BlockPos passed is (layer, z, x)
=> Fixed: the BlockPos passed to isBeaconBase

patches/minecraft/net/minecraft/entity/Entity.java.patch, patches/minecraft/net/minecraft/entity/player/EntityPlayerMP.java.patch, src/main/java/net/minecraftforge/common/ForgeHooks.java, src/main/java/net/minecraftforge/event/entity/EntityTravelToDimensionEvent.java, src/main/resources/forge_at.cfg, src/test/java/net/minecraftforge/test/EntityTravelToDimensionEventTest.java
This event fires before an entity travels to a dimension. Along with it comes the entity traveling to the dimension and the dimension id. I would like to be able to use this event in my mod to be able to cancel travelling to the nether/end. However, I see that it may have purpose for other mods which add their own dimensions and they wish to do something before they change to the dimension.
EntityMinecartContainer overrides Entity.travelToDimension (where this event is fired), but calls the super after it changes a single variable. This variable is dropContentsWhenDead. This is also a private variable, so for me to revert this value change I needed to add it to the access transformer.
I have put a test mod in the test directory which demonstrates stopping any entities from travelling …
=> [1.8.9] Add EntityTravelToDimensionEvent

src/main/java/net/minecraftforge/fml/common/asm/transformers/deobf/FMLDeobfuscatingRemapper.java
When running under Eclipse, for some bizarre reason JDT decorates some internal lamba local variables with invalid signature token `!*`. This isn't normally a problem since the signature is generally ignored, but the deobf transformer causes it to be visited and ASM's `SignatureReader` chokes on it.
This change basically just has the remapper strip the invalid signature so that the adapter doesn't shit the bed.
=> Fix ASM SignatureReader choking on invalid lambda local var signatures emitted by JDT

src/main/java/net/minecraftforge/fml/common/eventhandler/ASMEventHandler.java
https://bugs.openjdk.java.net/browse/JDK-8087309
Workaround for a JVM bug preventing constant folding. As event invocation is a hot code path, it seems worth fixing.
The change could be reduced to swapping `(owner != null && GETCONTEXT)` with `(GETCONTEXT && owner != null)`, but replacing the two ifs by using a ternary operator seemed cleaner.
=> Workaround JDK-8087309: Constant folding "static final boolean" is incomplete

patches/minecraft/net/minecraft/client/renderer/EntityRenderer.java.patch, src/main/java/net/minecraftforge/client/ForgeHooksClient.java
Fixes [the NPE](http://pastebin.com/egAXxAxB) caused by https://github.com/MinecraftForge/MinecraftForge/pull/2467.
=> Fix the entity shader hook

src/main/java/net/minecraftforge/client/model/ModelLoader.java, src/main/java/net/minecraftforge/common/ForgeModContainer.java, src/main/java/net/minecraftforge/fluids/FluidRegistry.java, src/main/java/net/minecraftforge/fluids/FluidUtil.java, src/main/java/net/minecraftforge/fluids/UniversalBucket.java, src/main/java/net/minecraftforge/items/IItemHandler.java, src/main/java/net/minecraftforge/items/ItemHandlerHelper.java, src/main/java/net/minecraftforge/items/wrapper/CombinedInvWrapper.java, src/main/java/net/minecraftforge/items/wrapper/EmptyHandler.java, src/main/java/net/minecraftforge/items/wrapper/InvWrapper.java, src/main/java/net/minecraftforge/items/wrapper/PlayerArmorInvWrapper.java, src/main/java/net/minecraftforge/items/wrapper/PlayerInvWrapper.java, src/main/java/net/minecraftforge/items/wrapper/PlayerMainInvWrapper.java, src/main/java/net/minecraftforge/items/wrapper/SidedInvWrapper.java, src/main/resources/assets/forge/lang/en_US.lang, src/test/java/net/minecraftforge/debug/DynBucketTest.java
The bucket has to be enabled BEFORE the pre-init stage is reached. This is done by calling FluidRegistry.enableUniversalBucket.
Mods can add fluids to be supported by the bucket through FluidRegistry.addBucketForFluid.
During PreInit Forge adds the bucket IF IT IS ENABLED. It is registered as forge:bucketFilled.
The universal bucket uses the Dynamic Bucket Model.
The universal bucket is NOT in the FluidContainerRegistry.
The bucket handles filling itself through the FillBucket event, and placing fluid through rightclick.
The FluidUtil provides the functions needed to interact with FluidContainerItems as well as the FluidContainerRegistry. See SimpleTank implementation in the test mod.
The Universal Bucket does NOT replace the vanilla empty bucket, and therefore does not convert the empty …
=> Add an universal bucket.

patches/minecraft/net/minecraft/world/chunk/Chunk.java.patch
Capture getLightOpacity prior to removing the tile entity.
=> Fix bug with getLightOpacity based on TileEntities,

patches/minecraft/net/minecraft/client/renderer/InventoryEffectRenderer.java.patch
Allows potions to _actually_ customize their rendering without the hook being useless.
Closes #2473.
=> Fix Potion.shouldRenderInvText

src/main/java/net/minecraftforge/client/model/ModelLoader.java
Fucked up the order in which things are registered/called. Prevents MC from trying to load the default-model for the universal bucket item instead of using the forgebucket model on the initial loading pass.
=> Fix universal bucket logging an exception

patches/minecraft/net/minecraft/tileentity/TileEntityFurnace.java.patch
For some reasons, furnaces store burn times as shorts, and fields and whole registry system are integers. 
Increased actual maximum fuel burn time from max short to max int.
Backwards compatible.
=> Increased actual maximum fuel burn time

patches/minecraft/net/minecraft/world/WorldServer.java.patch, src/main/java/net/minecraftforge/event/world/WorldEvent.java
Followup of #2496
Also expanded the events documentation.
=> Fix WordServer.canCreatureTypeSpawnHere not using Forge Events.

patches/minecraft/net/minecraft/client/Minecraft.java.patch, patches/minecraft/net/minecraft/network/NetHandlerPlayServer.java.patch, patches/minecraft/net/minecraft/server/management/ItemInWorldManager.java.patch, src/main/java/net/minecraftforge/common/ForgeHooks.java, src/main/java/net/minecraftforge/event/ForgeEventFactory.java, src/main/java/net/minecraftforge/event/entity/player/PlayerInteractEvent.java, src/test/java/net/minecraftforge/test/PlayerInteractEventLocalTest.java
This PR adds the ability to obtain the locally clicked position for some interact events.
The local position refers to where on the face of the block the click took place, and can be very useful information for mods to have.
I specifically made this PR so that SpongeForge can grab it from the event, as the SpongeAPI interact event contains a method to grab this information.
=> Added local click position to PlayerInteractEvent. Fixes #2482

src/main/java/net/minecraftforge/common/util/EnumHelper.java
1.9 ArmorMaterial now requires a SoundEvent for the equip sound.
=> 1.9: Fixed registering armor materials through EnumHelper exploding

patches/minecraft/net/minecraft/client/Minecraft.java.patch, patches/minecraft/net/minecraft/client/renderer/color/BlockColors.java.patch, patches/minecraft/net/minecraft/client/renderer/color/ItemColors.java.patch
This is an altered version of @Vazkii's https://github.com/MinecraftForge/MinecraftForge/pull/2546, making the changes as suggested in the comments. Found myself needing this for BoP so I thought I might as well spare the trouble of resubmitting this for a third time
=>  BlockColors and ItemColors no longer assume non-Vanilla id constancy. Added a getter for ItemColors.

patches/minecraft/net/minecraft/entity/ai/EntityAIAttackMelee.java.patch
Since 1.8 forge it was adding forge based path penalty to targetX instead of delayCounter, this fixes that, for the 1.9 branch at least.
I realize the forge based feature is default set to off since mojang had implemented their own version of failed path penalty, but good to fix it either way incase it's decided that mojangs version is not enough.
I've tested a workspace with the adjusted patch used and it has no compile issues.
=> Fix for patch targetting the wrong field to change for failed pathfinding penalty

patches/minecraft/net/minecraft/entity/player/EntityPlayer.java.patch
In 1.8.9 the call goes to getDisplayNameString() so that any changes from the PlayerEvent.NameFormat event are being take into account.
In this patch the call goes to func_70005_c_() which is the getter for the GameProfile name.
I changed it back.
Sorry if you do not want to accept it because it is a one-liner.
=> Fix the EntityPlayer patch

patches/minecraft/net/minecraft/block/BlockCrops.java.patch
directly access to field `AGE` -> call to method `getAge`, because beetroots use a different PropertyInteger for age.
=> [1.9] Fix #2555

patches/minecraft/net/minecraft/entity/player/EntityPlayer.java.patch
Calling `shouldRiderFaceForward` on `getAttackingEntity` is probably not what is intended here. 1.8.9 uses `this.ridingEntity`, which is a getter in 1.9 now.
=> Fix broken patch in EntityPlayer.updateRidden

patches/minecraft/net/minecraft/client/Minecraft.java.patch
It used to be called for both key-up and key-down states prior to 1.9, so I assume Vanilla's changes to F3 behavior broke the patch.
This patch just moves the fireKeyInput() line out of the getEventKeyState() condition above so it gets called for both states again.
=> [1.9] Fix KeyInputEvent only being fired if Keyboard.getEventKeyState() is false

patches/minecraft/net/minecraft/block/BlockRailBase.java.patch, patches/minecraft/net/minecraft/entity/item/EntityMinecart.java.patch
This was missing from the 1.8 version of Forge.
The 1.9 version is also missing it. I can make another PR for that if needed.
In 1.7 the function was called getBasicRailMetadata(), I've renamed it getRailDirection().
=> Add missing Minecart/Track hook.

patches/minecraft/net/minecraft/client/entity/EntityPlayerSP.java.patch
With the vanilla code, it is impossible to make a player collide less than 1 block tall, as it will always check the block above for headroom.
This PR adds in a check to see if the player height is less than 1 block, and if so, does not check the block above for headroom.
=> Fixed players smaller than 1 block not being able to walk under overhang

patches/minecraft/net/minecraft/entity/EntityLivingBase.java.patch, patches/minecraft/net/minecraft/entity/passive/EntityHorse.java.patch, patches/minecraft/net/minecraft/entity/player/EntityPlayer.java.patch, src/main/java/net/minecraftforge/items/ItemStackHandler.java, src/main/java/net/minecraftforge/items/wrapper/PlayerArmorInvWrapper.java, src/main/java/net/minecraftforge/items/wrapper/PlayerInvWrapper.java, src/main/java/net/minecraftforge/items/wrapper/PlayerMainInvWrapper.java, src/main/java/net/minecraftforge/items/wrapper/PlayerOffhandInvWrapper.java, src/main/java/net/minecraftforge/items/wrapper/RangedWrapper.java
This is so that modders don't have to keep wrapping around vanilla entities again and again to access them from capability-oriented code. They can assume that these will always work.
* EntityLivingBase
* Array for armor, array for both hands
* Expose armor from horizontal faces, hands from vertical faces, joined from null face
* EntityHorse
* IInventory AnimalChest
* Expose wrapper AnimalChest from all faces and null face
* EntityPlayer
* InventoryPlayer has array for armor, one-long array for offhand, array for main.
* Expose main from vertical faces, offhand+armor from horizontal faces, joined from null face.
=> Expose IItemHandler on vanilla entities

src/main/java/net/minecraftforge/common/ForgeHooks.java
1.8.9: 
https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/common/ForgeHooks.java#L544
Note that joinEntityItemWithWorld is a NO-OP on the clientside (for EntityPlayerSP)
1.9:
https://github.com/MinecraftForge/MinecraftForge/blob/1.9/src/main/java/net/minecraftforge/common/ForgeHooks.java#L559
The item is spawned regardless of side.
This PR adds a remote check to fix that
=> [1.9] Fix double dropping of items. Closes #2549

src/main/java/net/minecraftforge/fml/common/LoadController.java
The default behavior of the Google event bus just logs a single line to a java.util.Logger where it is likely to be not noticed. This passes the exception back to FML so it can handle it appropriately.
=> Pass exceptions thrown in mod event buses back to FML to handle appropriately 

patches/minecraft/net/minecraft/entity/EntityList.java.patch
Fix mod SpawnEggs only spawning pigs by using `EntityList.createEntityByName` instead of `func_188429_b` which relies on int IDs.
Also add a data fixer to upgrade old spawn eggs from 1.8 to the new format. To enable that `GameRegistry.registerDataFixer` was added as well.
If you want me to split out the `registerDataFixer` into a separate PR I can do so.
Fixes #2581.
=> Fix mod spawn eggs and EntityList.func_188429_b

src/main/java/net/minecraftforge/fluids/BlockFluidFinite.java
When `BlockFluidFinite#drain` is called with a `doDrain` argument of `true`, the block is removed from the world before the `FluidStack` is created. This causes the returned `FluidStack` to be created with an amount of 0, since `getQuantaPercentage` uses the in-world state (which is now air instead of the fluid).
This PR moves the `FluidStack` creation to the top of the method, before the block is removed from the world.
=> Allow finite fluids to be drained correctly

src/main/java/net/minecraftforge/common/ForgeHooks.java
I have no clue on earth how this originally worked when I was testing the fix the first time. I must've changed it to isServerWorld after testing.
As it turns out, EntityPlayerSP actually overrides isServerWorld to return true instead of `!worldObj.isRemote`, essentially rendering the fix completely useless.
Went back to a `!worldObj.isRemote` check and actually tested it every which way after the change, tossing from survival, creative, Q, CtrlQ, out of inventory, Q in inventory, CtrlQ in inventory. It actually works now.
Side note: Q-ing out of the hot bar in creative mode doesn't drop, and I checked with vanilla 1.9 and it doesn't either.
Sorry about that, let this be an example of why we should test every little change no matter how trivial .-.
=> Actually fix dupe drop

patches/minecraft/net/minecraft/block/BlockCrops.java.patch
1.9 added a `getMaxAge` (`func_185526_g`) method to BlockCrops which is used by beetroots. The getDrops patch did not respect those, causing beetroots to never drop anything.
Also use `getAge` (`func_185527_x`) method instead of directly accessing the block state value.
=> Fix BlockCrops.getDrops not respecting new age methods (for beetroots)

patches/minecraft/net/minecraft/client/gui/GuiScreen.java.patch, src/main/java/net/minecraftforge/fml/client/config/GuiConfig.java, src/main/java/net/minecraftforge/fml/client/config/GuiConfigEntries.java, src/main/java/net/minecraftforge/fml/client/config/GuiEditArray.java, src/main/java/net/minecraftforge/fml/client/config/GuiSelectString.java, src/main/java/net/minecraftforge/fml/client/config/GuiUtils.java
Fixes #2255 
Example of a large tooltip that shows many of the edge cases of this dynamic wrapping:
http://gfycat.com/FixedThornyBluetonguelizard
I also changed the Config Gui tooltips to use this dynamic wrapping tooltip with a max width of 300, instead of pre-wrapping the lines at 300 like it was doing before.
=> Make tooltips layout in the right direction, wrap if there is no room

patches/minecraft/net/minecraft/block/Block.java.patch
`Block.getPickBlock` calls this method by default (when nothing overrides it). Blocks without a corresponding Item will return an ItemStack with a null item here.
If `ForgeHooks.onPickBlock` gets an ItemStack with a null item, it warns about it. 
Returning null instead is easier for modders to handle (and is already handled as a normal case by `ForgeHooks.onPickBlock`).
Minecraft 1.7.10 and 1.8.9 both returned null from `getPickBlock` in this case.
=> Fix Block.getPickBlock returning an ItemStack with a null Item

src/main/java/net/minecraftforge/common/capabilities/Capability.java
This PR adds a couple of methods that allow accessing the storage directly from the capability. This reduces the extremely reduncant calls such as:
```java
NBTBase tag = CapabilityItemHandler.ITEM_HANDLER_CAPABILITY.getStorage().writeNBT(CapabilityItemHandler.ITEM_HANDLER_CAPABILITY, inventory, side);
```
to a more manageable:
```java
NBTBase tag = CapabilityItemHandler.ITEM_HANDLER_CAPABILITY.writeNBT(inventory, side);
```
Which I believe turns capability storage from something no one would ever use into an useful storage solution, without changing any of the semantics of the IStorage itself.
=> Make access to the Capability IStorage less annoying

patches/minecraft/net/minecraft/util/math/BlockPos.java.patch, patches/minecraft/net/minecraft/world/World.java.patch, patches/minecraft/net/minecraft/world/chunk/Chunk.java.patch, src/main/java/net/minecraftforge/common/util/BlockSnapshot.java
Minecraft 1.9 introduces `toImmutable` (`func_185334_h`) to `BlockPos`, removing the need for Forge's own method here.
=> Replace Forge's getImmutable method with the vanilla method

patches/minecraft/net/minecraft/block/Block.java.patch, patches/minecraft/net/minecraft/item/ItemBlock.java.patch
Prevents needing a custom ItemBlock just to add a Block tooltip
1.9 version of #2660
=> Forward ItemBlock#addInformation to Block#addInformation

patches/minecraft/net/minecraft/block/Block.java.patch, patches/minecraft/net/minecraft/client/renderer/chunk/RenderChunk.java.patch
Also cleaned up the javadocs a tad.
This is useful for mods with varied block subtypes (i.e. chisel). The state was already a variable in the place where canRenderInLayer was called, so it was a trivial patch. I think the use case is obvious, but if you need an example, just say so.
=> Add state param to Block.canRenderInLayer

src/main/java/net/minecraftforge/fml/common/registry/IForgeRegistryEntry.java
setRegistryName is called with a name argument which is derived from a ResourceLocation, which is case insensitive for domain names. As a result, mods with uppercase letters in their mod ids will always cause an error as a mismatch occurs between the lowercase registry name, and their uppercase mod id.
=> Fixed mismatched registry names and mod ids

patches/minecraft/net/minecraft/server/management/PlayerInteractionManager.java.patch
the onBlockHarvested method was being called twice, once from the call this pr removes and then again from the removedByPlayer method call below it
this fixes the logic running twice (i'm updating my mod and this was causing things to drop twice) although it might be better to only call that function when the flag is true (the block can actually be broken), if that's the case i can update my PR for that
=> onBlockHarvested is no longer called twice

patches/minecraft/net/minecraft/client/audio/SoundManager.java.patch
This PR moves the call to PlaySoundEvent to before ISound.createAccessor is called on the played sound, so that PositionedSound (and any other ISound that chooses to implement createAccessor) gets a chance to resolve the sound. Without this change, PositionedSound will NPE when trying to play the sound because the Sound field has not been set.
=> Fix PlaySoundEvent replacing a sound with PositionedSound causing an NPE.

src/main/resources/assets/forge/models/item/bucket.json, src/main/resources/assets/forge/models/item/bucket_milk.json
In this case pictures say more than thousand words.
Before:
After:
=> Fix dynbucket item transformation.

src/main/java/net/minecraftforge/items/CapabilityItemHandler.java
CapabilityItemHandler's readNBT would only read above Slot 1 and above, skipping the first slot, 0,  all together
=> Corrected CapabilityItemHandler.readNBT ignoring anything in slot 0

src/main/java/net/minecraftforge/items/CapabilityItemHandler.java
CapabilityItemHandler's readNBT would only read above Slot 1 and above, skipping the first slot, 0, all together
=> Corrected CapabilityItemHandler.readNBT ignoring anything in slot 0 in 1.9

src/main/java/net/minecraftforge/client/settings/KeyBindingMap.java
For instance, the hotkey for opening the inventory (e) wouldn't work while holding shift to sneak.
This also caused some weirdness with holding shift and mining, the block's mining animation wouldn't reset when you stop mining.
=> Fix some plain keybinds not working when a modifier is active

patches/minecraft/net/minecraft/world/BossInfo.java.patch, patches/minecraft/net/minecraft/world/BossInfoServer.java.patch
These methods can also be used by the server (see `BossInfoServer`, it sends packets to the client but the methods are annotated with `@SideOnly(Side.CLIENT)`).
=> Remove @SideOnly(Side.CLIENT) from BossInfo/BossInfoServer methods

src/main/java/net/minecraftforge/oredict/OreDictionary.java
I've added the following entries to the ore dictionary:
- Prismarine Shard ( `"gemPrismarine"` )
- Prismarine Crystals ( `"dustPrismarine"` )
- Prismarine Block ( `"blockPrismarine"` )
- Prismarine Brick ( `"blockPrismarineBrick"` )
- Dark Prismarine ( `"blockDarkPrismarine"` )
- Nether Wart ( `"cropNetherWart"` )
- Sugarcane ( `"sugarcane"` )
- Paper ( `"paper"` )
- Ender Pearl ( `"enderpearl"` )
- Bone ( `"bone `)
- Gunpowder ( `"gunpowder `)
- String ( `"string"` )
- Nether Star ( `"netherStar"` )
- Leather ( `"leather"` )
- Feather ( `"feather"` )
- Egg ( `"egg"` )
- End Stone ( `"endstone"` )
- Torch ( `"torch"` )
I've also organized the registration and replacement code.
As suggested below, I brought in #2306 and #2480 as well in order to consolidate additions to default OD entries, …
=> Update ore dictionary

src/main/java/net/minecraftforge/common/ForgeChunkManager.java
Someone missed the ! from the check, so atm as soon as any world unloads, chunk loading for other worlds starts to crash.
=> Fix ForgeChunkManager world unloading check

patches/minecraft/net/minecraft/client/renderer/InventoryEffectRenderer.java.patch, src/main/java/net/minecraftforge/client/event/GuiScreenEvent.java
=> [1.9] Add cancelable event for Potions shifting the gui position

src/main/java/net/minecraftforge/common/BiomeDictionary.java, src/main/java/net/minecraftforge/common/ForgeHooks.java
Using the latest MCP snapshots causes a wildcard import conflict in Forge because all static final names have been renamed to UPPER_CASE. It also seems that static imports aren't getting remapped properly.
This PR fixes the problem. Alternatively I did this and also updated the Forge mappings in https://github.com/matthewprenger/MinecraftForge/commit/6a290f908ca6f4d1147b3bb1446bdb3439bb4771. Let me know if you want that PR'ed instead.
=> Fix import static use with net.minecraft classes

patches/minecraft/net/minecraft/client/settings/GameSettings.java.patch, src/main/java/net/minecraftforge/client/settings/KeyModifier.java
Fixes this log spam: https://gist.github.com/gigaherz/e8ddabd8a8ebff0aeebdd345a0911e16
Previously, there was a `NOT_SUPPORTED` modifier, but it was removed when keybind support was added for all of vanilla. 
This will convert invalid keybind modifiers to `NONE` instead of spamming the log and resetting them to default values.
=> Fix log spam from invalid key modifiers

src/main/java/net/minecraftforge/client/model/ForgeBlockStateV1.java
The first-person left-hand rotation was a little bit of.
Once again, pictures will explain it a better:
Before:
After:
=> Fix forge:default-block transformation.

patches/minecraft/net/minecraft/client/gui/GuiBossOverlay.java.patch, src/main/java/net/minecraftforge/client/ForgeHooksClient.java, src/main/java/net/minecraftforge/client/event/RenderGameOverlayEvent.java
New version of #2578 
1.9 changed how boss bars are rendered. This quick PR adds in a subcategory to RenderGameOverlayEvent that fires whenever a single boss bar is rendered. Canceling the event will cause that single bar to not render, allowing you to perform custom rendering logic in its stead.
Botania needs this because it does custom rendering for its own bosses (Replaces the bar entirely with its own + shader + extra rendering)
Unfortunately, BossInfoLerping gives you almost no info (you don't even know what entity you're rendering a bar for), but that's out of the scope of this PR. With this, I can have enough info to do what needs to be done.
Thanks!
=> Boss bar render event

src/main/java/net/minecraftforge/items/VanillaDoubleChestItemHandler.java, src/main/java/net/minecraftforge/items/wrapper/SidedInvWrapper.java
Fix DoubleChestItemHandler not implementing IItemHandlerModifiable
SidedInvWrapper is a bug. DoubleChestItemHandler needs this to be able to be used with SlotItemHandler and chests should probably have it to begin with. (the single inventories do)
=> Fix SidedInvWrapper accessing wrong slots for setStackInSlot.

patches/minecraft/net/minecraft/world/chunk/Chunk.java.patch
Currently, all blocks placed by players that are not TE's run physics twice. Blocks that contain a TileEntity are not affected due to a check in 'ForgeHooks.onPlaceItemIntoWorld'.
In order to fix the problem, 'Chunk.setBlockState' will now verify if blocks are being captured before running onBlockAdded and if so, only run physics if the block has a tileentity. This check also prevents blocks such as TNT's from running its physics (explosion) when placement event is cancelled.
=> Only run block physics for TileEntities while capturing block placement.

patches/minecraft/net/minecraft/world/World.java.patch
This resolves a bug in 'World.markAndNotifyBlock' where the wrong blockstate was being passed to notifyNeighborsRespectDebug.
=> Fix wrong blockstate being passed to notifyNeighborsRespectDebug.

src/main/java/net/minecraftforge/common/util/BlockSnapshot.java
This change makes sure the updated tileentity is saved properly within the
chunk during restores.
=> Call markDirty when restoring blocks with TileEntities.

patches/minecraft/net/minecraft/client/renderer/texture/TextureMap.java.patch
Currently ````TextureMap.registerSprite```` checks to see if it already has a sprite with the same location by passing the ````ResourceLocation```` object directly into the map of sprites - which has a key type of ````String```` and so always fails to find an existing entry. This results in replacing the previous ````TextureAtlasSprite```` entry with a new one, forgetting the old one and never stitching it. This can be an issue for mods that register the same sprite location multiple times in different places.
=> [1.9] Fix registering sprites multiple times ignoring all but the last

patches/minecraft/net/minecraft/world/gen/ChunkProviderEnd.java.patch, patches/minecraft/net/minecraft/world/gen/ChunkProviderHell.java.patch, patches/minecraft/net/minecraft/world/gen/ChunkProviderOverworld.java.patch, src/main/java/net/minecraftforge/event/ForgeEventFactory.java
I ran into an extremely puzzling issue:
The code is written to randomly pepper and world with hives, but my hives were placing themselves in the exact same way in every chunk in huge batches, and then none for long stretches.
Turns out `rand` parameter I got from the `PopulateChunkEvent.Post` was returning the same values every time my world populating code was called!
The vanilla MapGen classes all call `world.setRandomSeed` during normal chunk population. It sort of looks like they're setting it with the chunk positions, but no. The params they give to `setRandomSeed` are identical many many times in a row.
Additionally, the `ForgeEventFactory.onChunkPopulate` was using `world.rand` for its rand parameter instead of the chunk-and-world-seeded one used for all the other world populating …
=> Fix the rand given to PopulateChunkEvent

src/main/java/net/minecraftforge/client/model/ItemTextureQuadConverter.java, src/main/java/net/minecraftforge/fluids/Fluid.java, src/main/java/net/minecraftforge/fluids/FluidUtil.java, src/main/java/net/minecraftforge/fluids/UniversalBucket.java
Fixes #2858
Adds the sounds when picking up liquids with a bucket #2821
For custom sounds when interacting with tanks, things get difficult.. Minecraft doesn't like it that the itemstack is manipulated directly for fluid containers and doesn't properly process the packet and doesn't set the animation if we execute the bucket filling/emptying remote too. But we get sounds for it then, that could send an event.
=> Fix Bucket rendering and add sound

patches/minecraft/net/minecraft/util/ScreenShotHelper.java.patch
On most windows machines, the "link" put in chat after taking a screenshot fails to open up the screenshot image.
This is because ScreenshotHelper gets passed mcDataDir, which most of the time is simply `"./"` . Using this form of the local directory causes the path given by `new File(gameDirectory, "screenshots")` to look like `"./screenshots"` which when made absolute is something like `"C:/Path/To/Minecraft/./screenshots"`. For most purposes, this URI is valid, but when used for `Desktop.browse()` it fails. Calling `getCanonicalFile()` on the initial screenshots folder removes this redundant `"./"`.
=> Fix screenshot link paths on Windows

src/test/java/net/minecraftforge/test/EnumHelperTest.java
Ensures that EnumHelper methods are kept in sync with Enum Constructors
It correctly detects not enough parameters on ArmorMaterial and verifies that applying Vazkii's PR (https://github.com/MinecraftForge/MinecraftForge/pull/2874) makes the test go green.
=> Add Unit Test to detect mismatches between EnumHelper and Enum ctor

patches/minecraft/net/minecraft/item/ItemAxe.java.patch
Seeing as the values being set by it are floats, the constructor should take floats, not ints.
Will close #2902
=> Switch new ItemAxe constructor to use floats

patches/minecraft/net/minecraft/client/network/NetHandlerPlayClient.java.patch, patches/minecraft/net/minecraft/tileentity/TileEntity.java.patch
This PR simply adds a hook for when `SPacketChunkData` is read on the client, instead of having it directly call `readFromNBT`. The default implementation just calls `readFromNBT` so no behavior will change. This merely provides a hook for modders to have special behavior for their sync data, and to know when data is synced.
=> Add hook for TE data sync on client

patches/minecraft/net/minecraft/block/BlockRailBase.java.patch
The block being used is `pos.down()` but originally the position being passed into `isSideSolid` was `pos`, not `pos.down()`. This PR corrects that.
=> Pass the correct position into isSideSolid in BlockRailBase#canPlaceBlockAt

src/main/java/net/minecraftforge/client/model/ForgeBlockStateV1.java
Currently, items that use the forge:default-tool transformation are rendered too large when in entity form:
They are twice as large as they are supposed to be.
This is because the "GROUND" transform type (and "HEAD" as well for that matter) is missing from the transformation.
In vanilla, "item/handheld" has "item/generated" as parent, so it inherits its transformations. Seems like the inherited transformations have been forgotten here.
=> Fix forge:default-tool transformation

patches/minecraft/net/minecraft/client/gui/inventory/GuiContainer.java.patch, patches/minecraft/net/minecraft/inventory/Slot.java.patch, src/main/java/net/minecraftforge/items/SlotItemHandler.java
This fixes shift + double clicking items in Containers that use SlotItemHandler slots.
The vanilla way of directly comparing the Slot#inventory reference in GuiContainer#mouseReleased means that all SlotItemHandler slots are considered being in the same inventory, since they use the same dummy inventory. Which then means that shift + double clicking items in Containers using SlotItemHandler slots causes a shift + click on all the SlotItemHandler slots in the Container.
This is updated for the master branch and replaces #2804.
=> Add a Slot#isSameInventory() method

src/main/java/net/minecraftforge/fluids/FluidTank.java
This PR makes it easier to internally use a FluidTank that has input/output restrictions for external manipulation.
This only applies to people using the new restrictions abilities, FluidTanks still work the same way as before. If you add restrictions for external manipulation, you will want these new methods for internal manipulation.
=> Make it easier to use FluidTanks that have input/output restrictions

patches/minecraft/net/minecraft/server/management/PlayerChunkMapEntry.java.patch, patches/minecraft/net/minecraft/world/gen/ChunkProviderServer.java.patch, src/main/java/net/minecraftforge/common/chunkio/ChunkIOExecutor.java, src/main/java/net/minecraftforge/common/chunkio/ChunkIOProvider.java, src/main/java/net/minecraftforge/common/chunkio/QueuedChunk.java, src/main/resources/forge.exc
Replacement for #2926 
Since the update to Minecraft 1.9.4 chunks were actually never loaded asynchronously because a sync request was always made from the PlayerChunkMap shortly after the chunk had been queued.
- PlayerChunkMapEntry now only loads chunks synchronously *after* the chunk failed to load asynchronously.
- Fixed some minor bugs that caused "Attempted to dequeue chunk" messages
- Simplified ChunkProviderServer patch. loadChunk no longer generates chunks, so there is no need to handle that.
- Moved loader and provider to ChunkIOProvider so there is no need for "hashCode abuse"
**Note:** The patch is mostly based on the changes I made for the [SpongeVanilla port of asynchronous chunk loading](https://github.com/SpongePowered/SpongeVanilla/pull/243). I don't think they should …
=> Fix asynchronous chunk loading

patches/minecraft/net/minecraft/client/gui/achievement/GuiAchievements.java.patch
Fixed arrows not showing in AchievementPages other then the default one.
Here are two images showing with and without the fix: http://imgur.com/a/rUbTp
=> Fixed arrows not showing in non default AchievementPages

patches/minecraft/net/minecraft/world/storage/loot/LootContext.java.patch
As title, easy enough.
Useful for custom LootFunctions and LootConditions that need the world, but you can't get it because all the entities are null (for example, chest gen tables. No looted entity, no killer either)
Makes it possible to have loot tables that do different things based on the world (raining/nether/etc.)
Closes #2916
=> Add getter for the world to LootContext

src/main/java/net/minecraftforge/fluids/FluidUtil.java, src/main/java/net/minecraftforge/fluids/UniversalBucket.java, src/main/java/net/minecraftforge/fluids/capability/templates/FluidHandlerItemStack.java, src/main/java/net/minecraftforge/fluids/capability/templates/FluidHandlerItemStackSimple.java, src/main/java/net/minecraftforge/fluids/capability/wrappers/FluidBucketWrapper.java, src/main/java/net/minecraftforge/fluids/capability/wrappers/FluidContainerRegistryWrapper.java
Turns out I wasn't preserving capability data when swapping the item before, the compatibility wrappers just write straight to nbt so it worked for those.
~~This adds a method to ItemStack to make it possible to correctly swap ItemStacks that have capabilities. I don't really like ItemStack swapping so I put a disclaimer comment on it.~~
This uses the existing itemStack serialize/deserialize to swap the stack.
=> Fix #2961 Capability data is not preserved by fluid handler interactions

patches/minecraft/net/minecraft/entity/monster/EntityZombie.java.patch
Since vanilla does not know about `VILLAGER_TYPE_STR` the IDs won't match up causing (among other things probably) a CCE in the zombie renderer, causing zombies to be invisible.
By moving the new DataParameter to the end of the list it gets an ID which is unknown to vanilla and simply gets ignored.
=> Fix DataParameter mixup when vanilla clients are connected 

patches/minecraft/net/minecraft/init/Bootstrap.java.patch, src/main/java/net/minecraftforge/fluids/DispenseFluidContainer.java, src/main/java/net/minecraftforge/fluids/UniversalBucket.java
Tested many variations.
If the universal bucket is registered, everything can be picked up and placed.
If it isn't, the vanilla fluids can be picked up and placed, but the modded ones cannot. The empty bucket is ejected as an item instead of turning modded fluids into water or lava.
If milk is registered as a fluid block, it can be placed and picked up. If it is not, the milk bucket is ejected as an item.
All of these behaviors are abstracted away by IFluidHandler, you can see the logic here has no special cases.
=> Fix #2918 Make dispensers with buckets work with modded fluids

patches/minecraft/net/minecraft/item/ItemStack.java.patch
Itemstack serialize + deserialize is being used to set an itemstack's properties and capabilities from another stack.
Currently, deserialize will not change the itemStack's stackTagCompound when the target stack's stackTagCompound is null.
This PR sets the itemstack stackTagCompound to null in that case.
Some empty fluid containers (one in forestry) use null nbt when they are empty and have nbt when filled. this bug makes it so that when it's emptied, it still has nbt and basically acts like it has infinite fluid.
=> Fix ItemStack deserialization can't clear the stackTagCompound 

src/main/java/net/minecraftforge/fml/client/GuiModsMissing.java, src/main/java/net/minecraftforge/fml/common/MissingModsException.java, src/main/java/net/minecraftforge/fml/common/versioning/Restriction.java, src/main/java/net/minecraftforge/fml/common/versioning/VersionRange.java, src/main/resources/assets/forge/lang/en_US.lang
I realize the log has all the information you need, but I see this error screen pasted all over the place with questions about it, so I figure it can use some improvements to help beginners out and cut down on the reports.
Before:
After:
_edit: this is the final result after some discussion below_
I removed the "Forge Mod Loader blah blah" since it doesn't say anything and people stop reading there.
The message now prominently displays the mod that is missing its dependencies.
It formats the required version strings in a human-readable way (without requiring knowledge of the bracket/braces range notation). It also can display version ranges and maximum versions, which were not previously supported.
=> Improve the "missing mods" error screen

patches/minecraft/net/minecraft/entity/item/EntityItem.java.patch, patches/minecraft/net/minecraft/item/ItemStack.java.patch
Note: I left the logic in `ItemStack#areCapsCompatible` the way it is instead of condensing it into nested ternary operators because I felt for something that large, ease of understanding was more important than decreasing patch size.
=> Fix broken EntityItem merging for Items with capabilities

patches/minecraft/net/minecraft/entity/player/EntityPlayerMP.java.patch
There's inverted logic in a patch that causes guis to close constantly.
=> [1.10.0] Fix guis closing as soon as they are opened

patches/minecraft/net/minecraft/client/settings/GameSettings.java.patch
Integer.parseInt(s2) throws a NumberFormatException in the case of a KeyModifier being applied, as the input will be something like "2:SHIFT", causing the option to be skipped.
This fixes the _already existing patch that got broken during the 1.10 update_ to only run the Vanilla setKeyCode if no KeyModifier is saved.
=> [1.10] Fix keys with KeyModifier failing to load

src/main/java/net/minecraftforge/oredict/RecipeSorter.java
When someone doesn't register their recipe with the RecipeSorter it will often crash because the comparison does not handle UNKNOWN in a way that follows the comparison contract.
This PR keeps the same ordering, but handles UNKNOWN so that it will not crash.
=> Fix comparison stability of the Recipe Sorter with unknown recipes

src/main/java/net/minecraftforge/fluids/UniversalBucket.java
Vanilla water, lava, and milk buckets are already in the creative list. 
When the universal bucket adds all its subitems, it adds them a second time.
This PR stops the universal bucket from creating subitems for water, lava, and milk.
=> Remove duplicated universal buckets from the creative list

src/main/java/net/minecraftforge/fluids/FluidContainerRegistry.java
The `FluidContainerRegistry` incorrectly thinks that potions can be drained for water.
The water bottle and potions share an item. Before, only the water bottle could be filled and drained with water. This is a bug that appeared recently, when potions started using NBT instead of meta.  `FluidContainerRegistry` only checks meta, not NBT. This PR makes it check the item NBT too, so that only water bottles can be filled and emptied.
=> Fix FluidContainerRegistry handling potions as water bottles

patches/minecraft/net/minecraft/item/ItemBucket.java.patch
This fixes fluid capability handling for old buckets that don't use the universal bucket and inherit from  `ItemBucket`. This problem was found with EnderIO buckets in #3033.
When `FluidContainerRegistry` is removed, this can be simplified again.
=> Fix legacy handling for ItemBucket subclasses and non-universal buckets

src/main/java/net/minecraftforge/fluids/capability/wrappers/FluidBucketWrapper.java
This fixes a bug where milk buckets can be filled with water or lava when "milk" is not a registered fluid.
Found in #3033
=> Fix milk bucket is fillable with water or lava when milk is unregistered

patches/minecraft/net/minecraft/tileentity/MobSpawnerBaseLogic.java.patch, src/main/java/net/minecraftforge/event/ForgeEventFactory.java
Prevents crashes [like this](http://www.minecraftforge.net/forum/index.php/topic,40097.0.html). Also simplified the patch in the process (-1+4 to -1+1).
Let me know if you want this for 1.9.4 (master) as well.
=> Fix mob-spawners crashing for non-living entities

patches/minecraft/net/minecraft/block/BlockPistonMoving.java.patch
Reported [on the forums](http://www.minecraftforge.net/forum/index.php/topic,40189.0.html).
=> Restore (buggy?) behavior of vanilla BlockPistonMoving and ignore the drop chance

patches/minecraft/net/minecraft/world/gen/ChunkProviderServer.java.patch
Periodically a race condition in forge for 1.10/1.10.2 causes new chunks to be regenerated instead of loaded.  This causes larger structures such as villages to have incomplete components. As shown in Issue #3020 Buildings in village not fully forming.  When the structure was generated on the original version of the chunk, then overwritten by the duplicate. 
This patch ensures when ProvideChunk calls LoadChunk synchronously we always
attempt to load the chunk (if not cached) thus avoid the race condition without
changing the logic for async loading for chunks already saved to disk.
Thus this should retain the async functionality from PR #2946 (the logic modified in this PR) while preventing generation issues caused by the race condition.
Since this is a diff of a diff (of the code …
=> [1.10.x] Fix async race condition on new chunks (fixes #3020, rebase #3061)

patches/minecraft/net/minecraft/client/multiplayer/PlayerControllerMP.java.patch, patches/minecraft/net/minecraft/item/Item.java.patch, src/main/java/net/minecraftforge/client/ForgeHooksClient.java, src/test/java/net/minecraftforge/debug/ItemLayerModelDebug.java
This allows to keep breaking blocks if the NBT or similar changes.
The forever old problem with stuff that changes NBT data while mining blocks, like autorepair and RF and whatnot.
=> Add shouldCauseBlockBreakReset callback to Item.

patches/minecraft/net/minecraft/client/settings/GameSettings.java.patch
A modded hotkey is set with a modifier on by default (like JEI's `Control-O` hotkey) 
The player sets it to a hotkey with no modifier (like `O` by itself)
When loading the world, the default modifier (`Control`) will be applied to the player's hotkey.
It should have no modifier.
Set the modifier to NONE when loading from file and no modifier is set there.
Original bug reported here: https://github.com/mezz/JustEnoughItems/issues/365
=> Fix hotkey with default modifier loading wrong when set with no modifier

patches/minecraft/net/minecraft/block/BlockDynamicLiquid.java.patch, src/main/java/net/minecraftforge/event/ForgeEventFactory.java, src/main/java/net/minecraftforge/event/world/BlockEvent.java, src/main/java/net/minecraftforge/fluids/BlockFluidClassic.java, src/test/java/net/minecraftforge/test/CreateFluidSourceTest.java
When two fluid source blocks are next to a non-source block, add an event to allow mods to change the default behavior where water is "infinite" and other fluids are not.
=> [1.10.x] Add an event to control whether fluids can create source blocks

patches/minecraft/net/minecraft/client/renderer/texture/TextureMap.java.patch, patches/minecraft/net/minecraft/client/renderer/texture/TextureUtil.java.patch, src/test/java/net/minecraftforge/debug/TextureDump.java
This is another way to solve the issue stated in #3082
Basically, some modded textures are reducing the mipmap level of everything, making the game look terrible. I want to keep the mipmap level at the player's setting instead of letting these weird-size textures lower it.
mipmap level 0 (crop)
mipmap level 4 (crop)
Difference from the last PR:
- Forces all textures to be mipmapped, instead of causing missing textures. This means the odd-sized textures may have mipmap artifacts, but at least they are not missing.
- No config option (you can just turn off mipmapping and it will look like it did before)
Here are some examples of the artifacts introduced on strange textures:
16x16 no artifacts, works normally 
15x15 definitely seeing some artifacts, but at least it's not a missing texture …
=> Force mipmap even if textures are the wrong size

src/main/java/net/minecraftforge/fml/relauncher/FMLSecurityManager.java
See http://www.minecraftforge.net/forum/index.php/topic,40907.0.html for more info (Blackout == EyZox == me)
=> FMLSecurityManager IndexOutOfBoundException

patches/minecraft/net/minecraft/client/audio/SoundManager.java.patch
This is an update for 1.10.x of (https://github.com/MinecraftForge/MinecraftForge/pull/3063 and https://github.com/MinecraftForge/MinecraftForge/pull/2933)
https://bugs.mojang.com/browse/MC-35856
=> [1.10.x] Fixed sound paused/resume issue (Vanilla bug)

patches/minecraft/net/minecraft/block/Block.java.patch, patches/minecraft/net/minecraft/client/multiplayer/PlayerControllerMP.java.patch, patches/minecraft/net/minecraft/client/renderer/RenderGlobal.java.patch, patches/minecraft/net/minecraft/entity/Entity.java.patch, patches/minecraft/net/minecraft/entity/EntityLivingBase.java.patch, patches/minecraft/net/minecraft/entity/passive/EntityHorse.java.patch, patches/minecraft/net/minecraft/item/ItemBed.java.patch, patches/minecraft/net/minecraft/item/ItemBlock.java.patch, patches/minecraft/net/minecraft/item/ItemBlockSpecial.java.patch, patches/minecraft/net/minecraft/item/ItemDoor.java.patch, patches/minecraft/net/minecraft/item/ItemSlab.java.patch, patches/minecraft/net/minecraft/item/ItemSnow.java.patch
Clean, no-nonsense version of #3109 
Note that sometimes I requery the world when calling getSoundType because onBlockPlaced could have modified the world state since a state local variable was created
=> No-nonsense sensitive getSoundType

patches/minecraft/net/minecraft/world/biome/BiomeDesert.java.patch, patches/minecraft/net/minecraft/world/biome/BiomeForest.java.patch, patches/minecraft/net/minecraft/world/biome/BiomeJungle.java.patch, patches/minecraft/net/minecraft/world/biome/BiomePlains.java.patch, patches/minecraft/net/minecraft/world/biome/BiomeSavanna.java.patch, patches/minecraft/net/minecraft/world/biome/BiomeSnow.java.patch, patches/minecraft/net/minecraft/world/biome/BiomeSwamp.java.patch, patches/minecraft/net/minecraft/world/biome/BiomeTaiga.java.patch, src/main/java/net/minecraftforge/event/terraingen/DecorateBiomeEvent.java, src/test/java/net/minecraftforge/debug/DecorateEventDebug.java
Based off of #2009 this adds support for Decorate event hook for all biomes. This also adds in support for fossils and desert wells.
This uses the DecorateBiomeEvent.Decorate event so if result is set to DENY then nothing extra should decorate.
=> Update decorate for biomes to support Decorate event

src/main/java/net/minecraftforge/client/model/pipeline/IVertexConsumer.java, src/main/java/net/minecraftforge/client/model/pipeline/LightUtil.java, src/main/java/net/minecraftforge/client/model/pipeline/UnpackedBakedQuad.java, src/main/java/net/minecraftforge/client/model/pipeline/VertexBufferConsumer.java, src/main/java/net/minecraftforge/client/model/pipeline/VertexLighterFlat.java, src/main/java/net/minecraftforge/client/model/pipeline/VertexTransformer.java
Implementations of VertexBufferConsumer will need to add the new method but this resolves issues with consumers dropping sprites, which fixes potential crashes in dynamic model code, specifically now that extended state models are usable for damage rendering.
Fixes, https://github.com/SlimeKnights/TinkersConstruct/issues/2279
=> Fix Vertex Transformer for breaking models

patches/minecraft/net/minecraft/client/gui/GuiScreen.java.patch, patches/minecraft/net/minecraft/client/gui/inventory/GuiContainerCreative.java.patch, src/main/java/net/minecraftforge/client/event/RenderTooltipEvent.java, src/main/java/net/minecraftforge/fml/client/config/GuiUtils.java
This event provides a way to hook into tooltip rendering, where the GUI methods fall short. For instance, with this event, custom rendering could be done that would always match the true position of the tooltip box, without reproducing the calculations that led to it.
I will be adding javadocs come tomorrow, but I figured i'd put the code up for review now.
=> Add RenderTooltipEvent

patches/minecraft/net/minecraft/inventory/InventoryHelper.java.patch
This adjusts `InventoryHelper#spawnItemStack` to use `ItemStack#splitStack` instead of manually creating a new ItemStack instance, to avoid item stacks spawned into the world losing their capability data. Before this patch, when an item was dropped into the world via this method (for example when breaking a vanilla chest), the `EntityItem`'s item stack was missing any persistent capability data (i.e. data that gets stored in the `ForgeCaps` tag).
I decided to remove code that is now redundant due to the same checks and operations (copying the NBT tag, in particular) being performed in `splitStack`. If this is undesired due to the increased patch size, let me know, and I'll reduce it to the single line.
=> Make InventoryHelper#spawnItemStack use ItemStack#splitStack to avoid losing capability data

src/test/java/net/minecraftforge/debug/DynBucketTest.java, src/test/java/net/minecraftforge/debug/EnumPlantTypeTest.java, src/test/java/net/minecraftforge/debug/ForgeBlockStatesLoaderDebug.java, src/test/java/net/minecraftforge/debug/ItemLayerModelDebug.java, src/test/java/net/minecraftforge/debug/ItemTileDebug.java, src/test/java/net/minecraftforge/debug/LootTablesDebug.java, src/test/java/net/minecraftforge/debug/ModelAnimationDebug.java, src/test/java/net/minecraftforge/debug/ModelBakeEventDebug.java, src/test/java/net/minecraftforge/debug/ModelFluidDebug.java, src/test/java/net/minecraftforge/debug/ModelLoaderRegistryDebug.java, src/test/java/net/minecraftforge/debug/MultiLayerModelDebug.java, src/test/java/net/minecraftforge/debug/PotionRegistryDebug.java, src/test/java/net/minecraftforge/test/BrewingRecipeRegistryTest.java, src/test/java/net/minecraftforge/test/CreateFluidSourceTest.java, src/test/java/net/minecraftforge/test/EntityTravelToDimensionEventTest.java, src/test/java/net/minecraftforge/test/FluidHandlerTest.java, src/test/java/net/minecraftforge/test/NeighborNotifyEventTest.java, src/test/java/net/minecraftforge/test/NoBedSleepingTest.java, src/test/java/net/minecraftforge/test/PlayerInteractEventTest.java, src/test/java/net/minecraftforge/test/TestCapabilityMod.java, src/test/java/net/minecraftforge/test/WRNormalMod.java
Most of our test mods have bad IDs (uppercase) and are missing names or
versions. Forge produces a bunch of warnings in the console about this, which
makes it more likely that an important message will be missed.
=> Fix test mod IDs, names, and versions

patches/minecraft/net/minecraft/client/renderer/entity/RenderPlayer.java.patch
Vanilla allows you to use a bow in your offhand, but it's not visible to others or in third person. This simply takes what's done to the main hand and replicates it for the offhand, which was missing the BOW action.
Fixes [MC-88356](https://bugs.mojang.com/browse/MC-88356)
1.10 version of #2983
=> [1.10.x] Add support for offhand bow aiming animation

patches/minecraft/net/minecraft/block/Block.java.patch, patches/minecraft/net/minecraft/item/ItemBlock.java.patch, patches/minecraft/net/minecraft/item/ItemBlockSpecial.java.patch, patches/minecraft/net/minecraft/item/ItemDye.java.patch
Updated version of #2967.
Allows for setting the block state based on non-metadata `ItemStack` attribute such as NBT or Capabilities.
All Vanilla calls to the original method have been updated to call `getStateForPlacement`.
=> Add Block#getStateForPlacement, a stack aware version of onBlockPlaced

patches/minecraft/net/minecraft/block/BlockFarmland.java.patch, patches/minecraft/net/minecraft/entity/Entity.java.patch
This allows entities to override the new `canTrample` method to allow/disallow trampling of blocks.
Fixes #2510
=> Add method to check if an Entity can trample a Block

src/main/java/net/minecraftforge/event/AttachCapabilitiesEvent.java, src/main/java/net/minecraftforge/items/ItemHandlerHelper.java, src/test/java/net/minecraftforge/test/TestCapabilityMod.java
Update of #2980 to target the 1.10.x branch.
Edit 12-3-16:
Currently the canStack methods in ItemHandlerHelper preform a custom check to determine if the NBT tags are equal. The problem with this is capabilities are not taken into account. This PR replaces the custom check with a call to 'ItemStack.areItemStackTagsEqual' which checks capabilities. In addition, I expanded the TestCapMod to include ItemStacks with capability data. Note that only ItemStacks with the same capability data stack.
=> [1.10.x] Fix ItemHandlerHelper canStack methods not checking capabilities
